// Ereignisse der Menschheitsgeschichte.
// year: negative Zahlen = v. Chr.  |  approx: true = Jahr ist eine Schätzung ("ca.")
// image: Pfad zum Bild (SVG, WebP, JPG ... – max. ~50 KB pro Bild empfohlen)
const EVENTS = [
  { id: "rad", title: "Erfindung des Rades", year: -3500, approx: true, image: "img/rad.svg", fact: "Die ältesten Räder stammen aus Mesopotamien und Europa – zuerst wohl als Töpferscheibe." },
  { id: "pyramide", title: "Bau der Cheops-Pyramide", year: -2560, approx: true, image: "img/pyramide.svg", fact: "Die Große Pyramide von Gizeh war fast 4.000 Jahre lang das höchste Bauwerk der Welt." },
  { id: "olympia", title: "Erste Olympische Spiele der Antike", year: -776, image: "img/olympia.svg", fact: "Die Spiele in Olympia wurden zu Ehren des Zeus abgehalten." },
  { id: "mauer_china", title: "Einigung Chinas & Bau der Großen Mauer", year: -221, image: "img/mauer_china.svg", fact: "Kaiser Qin Shi Huang ließ ältere Mauerstücke zu einem Bollwerk verbinden." },
  { id: "caesar", title: "Ermordung Julius Caesars", year: -44, image: "img/caesar.svg", fact: "Caesar wurde an den Iden des März im römischen Senat erstochen." },
  { id: "vesuv", title: "Vesuv-Ausbruch zerstört Pompeji", year: 79, image: "img/vesuv.svg", fact: "Die Asche konservierte die Stadt so gut, dass man sie heute noch besichtigen kann." },
  { id: "karl", title: "Kaiserkrönung Karls des Großen", year: 800, image: "img/karl.svg", fact: "Papst Leo III. krönte Karl am Weihnachtstag in Rom zum Kaiser." },
  { id: "buchdruck", title: "Gutenberg erfindet den Buchdruck", year: 1450, approx: true, image: "img/buchdruck.svg", fact: "Mit beweglichen Metalllettern konnten Bücher erstmals schnell vervielfältigt werden." },
  { id: "kolumbus", title: "Kolumbus erreicht Amerika", year: 1492, image: "img/kolumbus.svg", fact: "Eigentlich wollte Kolumbus einen westlichen Seeweg nach Indien finden." },
  { id: "luther", title: "Luthers 95 Thesen – Reformation", year: 1517, image: "img/luther.svg", fact: "Martin Luther kritisierte den Ablasshandel der Kirche." },
  { id: "newton", title: "Newton veröffentlicht das Gravitationsgesetz", year: 1687, image: "img/newton.svg", fact: "In seinem Werk „Principia“ beschrieb Newton die Gesetze der Bewegung und Schwerkraft." },
  { id: "dampfmaschine", title: "James Watts verbesserte Dampfmaschine", year: 1769, image: "img/dampfmaschine.svg", fact: "Sie wurde zum Motor der Industriellen Revolution." },
  { id: "usa", title: "Unabhängigkeitserklärung der USA", year: 1776, image: "img/usa.svg", fact: "Am 4. Juli sagten sich 13 Kolonien von Großbritannien los." },
  { id: "franz_revolution", title: "Französische Revolution – Sturm auf die Bastille", year: 1789, image: "img/franz_revolution.svg", fact: "„Freiheit, Gleichheit, Brüderlichkeit“ wurde zum Leitspruch." },
  { id: "eisenbahn", title: "Erste Eisenbahn in Deutschland", year: 1835, image: "img/eisenbahn.svg", fact: "Der „Adler“ fuhr von Nürnberg nach Fürth." },
  { id: "darwin", title: "Darwins Evolutionstheorie", year: 1859, image: "img/darwin.svg", fact: "In „Über die Entstehung der Arten“ erklärte Darwin die natürliche Auslese." },
  { id: "telefon", title: "Erfindung des Telefons", year: 1876, image: "img/telefon.svg", fact: "Alexander Graham Bell meldete das Patent an – Philipp Reis hatte schon vorher ein Gerät gebaut." },
  { id: "gluehbirne", title: "Edisons Glühbirne", year: 1879, image: "img/gluehbirne.svg", fact: "Edison entwickelte eine langlebige Glühlampe mit Kohlefaden." },
  { id: "automobil", title: "Benz baut das erste Automobil", year: 1886, image: "img/automobil.svg", fact: "Der Benz Patent-Motorwagen Nummer 1 hatte drei Räder." },
  { id: "roentgen", title: "Röntgen entdeckt die X-Strahlen", year: 1895, image: "img/roentgen.svg", fact: "Das erste Röntgenbild zeigte die Hand seiner Frau – mit Ehering." },
  { id: "motorflug", title: "Erster Motorflug der Brüder Wright", year: 1903, image: "img/motorflug.svg", fact: "Der erste Flug dauerte nur 12 Sekunden und war 37 Meter lang." },
  { id: "einstein", title: "Einsteins Relativitätstheorie", year: 1905, image: "img/einstein.svg", fact: "Mit der berühmten Formel E = mc² zeigte Einstein, dass Masse und Energie zusammenhängen." },
  { id: "amundsen", title: "Roald Amundsen erreicht den Südpol", year: 1911, image: "img/amundsen.svg", fact: "Der Norweger kam fünf Wochen vor seinem britischen Konkurrenten Robert Scott an." },
  { id: "titanic", title: "Untergang der Titanic", year: 1912, image: "img/titanic.svg", fact: "Das „unsinkbare“ Schiff kollidierte auf seiner Jungfernfahrt mit einem Eisberg." },
  { id: "fliessband", title: "Henry Ford führt das Fließband ein", year: 1913, image: "img/fliessband.svg", fact: "Statt rund 12 Stunden dauerte der Bau eines Ford Modell T nur noch etwa 1,5 Stunden." },
  { id: "wk1", title: "Beginn des Ersten Weltkriegs", year: 1914, image: "img/wk1.svg", fact: "Auslöser war das Attentat von Sarajevo auf den österreichischen Thronfolger." },
  { id: "oktoberrevolution", title: "Oktoberrevolution in Russland", year: 1917, image: "img/oktoberrevolution.svg", fact: "Die Bolschewiki unter Lenin übernahmen die Macht – später entstand daraus die Sowjetunion." },
  { id: "frauenwahlrecht", title: "Frauenwahlrecht in Deutschland", year: 1918, image: "img/frauenwahlrecht.svg", fact: "Im Januar 1919 durften Frauen zum ersten Mal in Deutschland wählen und gewählt werden." },
  { id: "hyperinflation", title: "Hyperinflation in Deutschland", year: 1923, image: "img/hyperinflation.svg", fact: "Das Geld verlor so schnell an Wert, dass ein Brot im Herbst Milliarden Mark kostete." },
  { id: "fernsehen", title: "Erste öffentliche Vorführung des Fernsehens", year: 1926, image: "img/fernsehen.svg", fact: "Der Schotte John Logie Baird zeigte in London die ersten bewegten Fernsehbilder." },
  { id: "lindbergh", title: "Lindbergh fliegt allein über den Atlantik", year: 1927, image: "img/lindbergh.svg", fact: "Charles Lindbergh flog in 33,5 Stunden ohne Zwischenstopp von New York nach Paris." },
  { id: "penicillin", title: "Entdeckung des Penicillins", year: 1928, image: "img/penicillin.svg", fact: "Alexander Fleming bemerkte, dass ein Schimmelpilz Bakterien abtötet." },
  { id: "boersencrash", title: "Börsencrash in New York", year: 1929, image: "img/boersencrash.svg", fact: "Der „Schwarze Donnerstag“ löste die Weltwirtschaftskrise aus." },
  { id: "reichstagsbrand", title: "Reichstagsbrand in Berlin", year: 1933, image: "img/reichstagsbrand.svg", fact: "Die Nationalsozialisten nutzten den Brand, um wichtige Grundrechte abzuschaffen." },
  { id: "hindenburg", title: "Absturz des Luftschiffs „Hindenburg“", year: 1937, image: "img/hindenburg.svg", fact: "Das Unglück in Lakehurst (USA) beendete das Zeitalter der großen Passagier-Luftschiffe." },
  { id: "wk2", title: "Beginn des Zweiten Weltkriegs", year: 1939, image: "img/wk2.svg", fact: "Am 1. September überfiel Deutschland Polen." },
  { id: "zuse", title: "Konrad Zuse baut den ersten Computer (Z3)", year: 1941, image: "img/zuse.svg", fact: "Die Z3 gilt als erster funktionsfähiger, frei programmierbarer Rechner der Welt." },
  { id: "hiroshima", title: "Atombombenabwurf auf Hiroshima", year: 1945, image: "img/hiroshima.svg", fact: "Der erste Einsatz einer Atomwaffe im Krieg; kurz darauf folgte Nagasaki." },
  { id: "indien", title: "Indien wird unabhängig", year: 1947, image: "img/indien.svg", fact: "Mahatma Gandhi hatte mit gewaltlosem Widerstand gegen die britische Herrschaft gekämpft." },
  { id: "menschenrechte", title: "Allgemeine Erklärung der Menschenrechte", year: 1948, image: "img/menschenrechte.svg", fact: "Die Vereinten Nationen verabschiedeten sie am 10. Dezember." },
  { id: "grundgesetz", title: "Das Grundgesetz – Gründung der Bundesrepublik", year: 1949, image: "img/grundgesetz.svg", fact: "Am 23. Mai 1949 trat die Verfassung der Bundesrepublik Deutschland in Kraft." },
  { id: "dna", title: "Entdeckung der DNA-Doppelhelix", year: 1953, image: "img/dna.svg", fact: "Watson und Crick beschrieben die Struktur – mit Hilfe von Rosalind Franklins Röntgenbildern." },
  { id: "everest", title: "Erstbesteigung des Mount Everest", year: 1953, image: "img/everest.svg", fact: "Edmund Hillary und Tenzing Norgay standen als Erste auf dem höchsten Berg der Erde." },
  { id: "bern", title: "„Das Wunder von Bern“", year: 1954, image: "img/bern.svg", fact: "Deutschland wurde mit einem 3:2 gegen Ungarn zum ersten Mal Fußball-Weltmeister." },
  { id: "sputnik", title: "Sputnik – erster künstlicher Satellit", year: 1957, image: "img/sputnik.svg", fact: "Der sowjetische Satellit löste den „Wettlauf ins All“ aus." },
  { id: "mauerbau", title: "Bau der Berliner Mauer", year: 1961, image: "img/mauerbau.svg", fact: "Die DDR riegelte am 13. August West-Berlin ab." },
  { id: "gagarin", title: "Juri Gagarin – erster Mensch im All", year: 1961, image: "img/gagarin.svg", fact: "Mit der Wostok 1 umrundete Gagarin in 108 Minuten einmal die Erde." },
  { id: "kubakrise", title: "Kubakrise", year: 1962, image: "img/kubakrise.svg", fact: "Sowjetische Atomraketen auf Kuba brachten die Welt 13 Tage lang an den Rand eines Atomkriegs." },
  { id: "mlk", title: "Martin Luther King: „I Have a Dream“", year: 1963, image: "img/mlk.svg", fact: "Vor über 250.000 Menschen in Washington forderte King gleiche Rechte für Schwarze und Weiße." },
  { id: "herz", title: "Erste Herztransplantation", year: 1967, image: "img/herz.svg", fact: "Der Chirurg Christiaan Barnard verpflanzte in Kapstadt erstmals ein menschliches Herz." },
  { id: "68er", title: "Studentenproteste der 68er-Bewegung", year: 1968, image: "img/68er.svg", fact: "Junge Menschen protestierten weltweit gegen den Vietnamkrieg und für mehr Mitbestimmung." },
  { id: "mondlandung", title: "Erste Mondlandung", year: 1969, image: "img/mondlandung.svg", fact: "Neil Armstrong betrat als erster Mensch den Mond." },
  { id: "email", title: "Die erste E-Mail wird verschickt", year: 1971, image: "img/email.svg", fact: "Ray Tomlinson führte dafür das @-Zeichen in E-Mail-Adressen ein." },
  { id: "mcdonalds", title: "Erste deutsche McDonald’s-Filiale öffnet", year: 1971, image: "img/mcdonalds.svg", fact: "Die erste Filiale in Deutschland eröffnete am 4. Dezember in München." },
  { id: "oelkrise", title: "Ölkrise – autofreie Sonntage", year: 1973, image: "img/oelkrise.svg", fact: "Weil Öl knapp und teuer wurde, waren in der Bundesrepublik an vier Sonntagen Autofahrten verboten." },
  { id: "vietnam", title: "Ende des Vietnamkriegs", year: 1975, image: "img/vietnam.svg", fact: "Mit der Einnahme Saigons endete der jahrzehntelange Krieg." },
  { id: "voyager", title: "Start der Raumsonden Voyager 1 und 2", year: 1977, image: "img/voyager.svg", fact: "Voyager 1 ist heute das am weitesten von der Erde entfernte von Menschen gebaute Objekt." },
  { id: "elvis", title: "Elvis Presley stirbt", year: 1977, image: "img/elvis.svg", fact: "Der „King of Rock ’n’ Roll“ starb mit 42 Jahren auf seinem Anwesen Graceland." },
  { id: "retortenbaby", title: "Erstes „Retortenbaby“ wird geboren", year: 1978, image: "img/retortenbaby.svg", fact: "Louise Brown war der erste Mensch, der durch künstliche Befruchtung im Labor entstand." },
  { id: "walkman", title: "Der Walkman kommt auf den Markt", year: 1979, image: "img/walkman.svg", fact: "Zum ersten Mal konnte man Musik überall mit Kopfhörern hören – auf Kassette." },
  { id: "freddie", title: "Freddie Mercury zieht nach München", year: 1979, approx: true, image: "img/freddie.svg", fact: "Der Queen-Sänger lebte von Ende der 1970er bis Mitte der 1980er überwiegend in München." },
  { id: "pocken", title: "Die Pocken sind ausgerottet", year: 1980, image: "img/pocken.svg", fact: "Dank weltweiter Impfungen war sie die erste Krankheit, die der Mensch vollständig besiegte." },
  { id: "lennon", title: "John Lennon wird erschossen", year: 1980, image: "img/lennon.svg", fact: "Der Ex-Beatle wurde am 8. Dezember vor seinem Wohnhaus in New York erschossen." },
  { id: "pc", title: "Der IBM Personal Computer erscheint", year: 1981, image: "img/pc.svg", fact: "Der „IBM PC“ machte den Computer zum Bürogerät." },
  { id: "cd", title: "Die CD kommt auf den Markt", year: 1982, image: "img/cd.svg", fact: "Die silberne Scheibe löste nach und nach Schallplatte und Kassette ab." },
  { id: "handy", title: "Das erste Handy kommt in den Handel", year: 1983, image: "img/handy.svg", fact: "Das Motorola DynaTAC wog rund 800 Gramm und kostete fast 4.000 Dollar." },
  { id: "ozon", title: "Entdeckung des Ozonlochs", year: 1985, image: "img/ozon.svg", fact: "Forscher entdeckten über der Antarktis eine dünne Stelle in der schützenden Ozonschicht." },
  { id: "liveaid", title: "Live-Aid-Konzert", year: 1985, image: "img/liveaid.svg", fact: "Konzerte in London und Philadelphia sammelten Geld gegen die Hungersnot in Äthiopien – Queen gab einen legendären Auftritt." },
  { id: "tschernobyl", title: "Reaktorunglück von Tschernobyl", year: 1986, image: "img/tschernobyl.svg", fact: "Eine radioaktive Wolke zog bis nach Mitteleuropa." },
  { id: "mauerfall", title: "Fall der Berliner Mauer", year: 1989, image: "img/mauerfall.svg", fact: "Am 9. November öffnete die DDR die Grenzübergänge." },
  { id: "wiedervereinigung", title: "Deutsche Wiedervereinigung", year: 1990, image: "img/wiedervereinigung.svg", fact: "Am 3. Oktober trat die DDR der Bundesrepublik bei." },
  { id: "hubble", title: "Das Hubble-Weltraumteleskop startet", year: 1990, image: "img/hubble.svg", fact: "Ohne störende Atmosphäre macht es gestochen scharfe Bilder ferner Galaxien." },
  { id: "www", title: "Das World Wide Web geht online", year: 1991, image: "img/www.svg", fact: "Tim Berners-Lee entwickelte das WWW am Forschungszentrum CERN." },
  { id: "eu", title: "Gründung der Europäischen Union", year: 1993, image: "img/eu.svg", fact: "Mit dem Vertrag von Maastricht wurde aus der Europäischen Gemeinschaft die EU." },
  { id: "mandela", title: "Nelson Mandela wird Präsident Südafrikas", year: 1994, image: "img/mandela.svg", fact: "Nach dem Ende der Apartheid durften erstmals alle Südafrikaner wählen." },
  { id: "cobain", title: "Kurt Cobain stirbt", year: 1994, image: "img/cobain.svg", fact: "Der Sänger von Nirvana („Smells Like Teen Spirit“) starb mit nur 27 Jahren." },
  { id: "dolly", title: "Klonschaf Dolly wird geboren", year: 1996, image: "img/dolly.svg", fact: "Dolly war das erste aus einer erwachsenen Körperzelle geklonte Säugetier." },
  { id: "harry_potter", title: "Der erste Harry-Potter-Band erscheint", year: 1997, image: "img/harry_potter.svg", fact: "„Harry Potter und der Stein der Weisen“ von J. K. Rowling wurde ein Welterfolg." },
  { id: "iss", title: "Baubeginn der Raumstation ISS", year: 1998, image: "img/iss.svg", fact: "Das erste Modul „Sarja“ wurde ins All geschossen – heute ist die ISS so groß wie ein Fußballfeld." },
  { id: "google", title: "Gründung von Google", year: 1998, image: "img/google.svg", fact: "Larry Page und Sergey Brin starteten die Suchmaschine in einer Garage in Kalifornien." },
  { id: "wikipedia", title: "Wikipedia geht online", year: 2001, image: "img/wikipedia.svg", fact: "Die freie Online-Enzyklopädie wird von Freiwilligen auf der ganzen Welt geschrieben." },
  { id: "euro", title: "Euro-Bargeld wird eingeführt", year: 2002, image: "img/euro.svg", fact: "Am 1. Januar löste der Euro u. a. die D-Mark ab." },
  { id: "genom", title: "Das menschliche Erbgut ist entschlüsselt", year: 2003, image: "img/genom.svg", fact: "Das Humangenomprojekt las die rund 3 Milliarden Bausteine unserer DNA aus." },
  { id: "facebook", title: "Gründung von Facebook", year: 2004, image: "img/facebook.svg", fact: "Mark Zuckerberg startete das soziale Netzwerk als Student an der Harvard-Universität." },
  { id: "tsunami", title: "Tsunami im Indischen Ozean", year: 2004, image: "img/tsunami.svg", fact: "Ein Seebeben löste am 26. Dezember eine Riesenwelle aus, die über 200.000 Menschen tötete." },
  { id: "merkel", title: "Angela Merkel wird erste Bundeskanzlerin", year: 2005, image: "img/merkel.svg", fact: "Sie regierte 16 Jahre lang – bis 2021." },
  { id: "youtube", title: "Das erste YouTube-Video wird hochgeladen", year: 2005, image: "img/youtube.svg", fact: "In „Me at the zoo“ filmte sich Mitgründer Jawed Karim 19 Sekunden lang vor Elefanten im Zoo von San Diego." },
  { id: "wm2006", title: "Fußball-WM in Deutschland – das „Sommermärchen“", year: 2006, image: "img/wm2006.svg", fact: "Deutschland feierte als Gastgeber und wurde Dritter." },
  { id: "smartphone", title: "Das erste iPhone wird vorgestellt", year: 2007, image: "img/smartphone.svg", fact: "Es machte Touchscreen-Smartphones massentauglich." },
  { id: "finanzkrise", title: "Weltfinanzkrise – Pleite von Lehman Brothers", year: 2008, image: "img/finanzkrise.svg", fact: "Der Zusammenbruch der US-Bank löste eine weltweite Wirtschaftskrise aus." },
  { id: "bitcoin", title: "Bitcoin – die erste Kryptowährung startet", year: 2009, image: "img/bitcoin.svg", fact: "Wer sich hinter dem Erfinder „Satoshi Nakamoto“ verbirgt, ist bis heute unbekannt." },
  { id: "arabischer_fruehling", title: "Beginn des Arabischen Frühlings", year: 2010, image: "img/arabischer_fruehling.svg", fact: "Proteste in Tunesien breiteten sich auf viele arabische Länder aus." },
  { id: "instagram", title: "Instagram geht online", year: 2010, image: "img/instagram.svg", fact: "Die Foto-App startete im Oktober zunächst nur für das iPhone – 2012 kaufte Facebook sie für 1 Milliarde Dollar." },
  { id: "fukushima", title: "Atomkatastrophe von Fukushima", year: 2011, image: "img/fukushima.svg", fact: "Ein Erdbeben und ein Tsunami zerstörten das Kraftwerk; Deutschland beschloss danach den Atomausstieg." },
  { id: "snapchat", title: "Snapchat geht online", year: 2011, image: "img/snapchat.svg", fact: "Das Besondere: Fotos verschwinden nach wenigen Sekunden wieder." },
  { id: "curiosity", title: "Mars-Rover Curiosity landet", year: 2012, image: "img/curiosity.svg", fact: "Der Rover in Autogröße fand Hinweise, dass es auf dem Mars einst Wasser gab." },
  { id: "gangnam", title: "„Gangnam Style“ erscheint auf YouTube", year: 2012, image: "img/gangnam.svg", fact: "Das Video des südkoreanischen Rappers PSY war das erste auf YouTube mit über einer Milliarde Aufrufen." },
  { id: "afd", title: "Gründung der AfD", year: 2013, image: "img/afd.svg", fact: "Die „Alternative für Deutschland“ wurde zunächst als eurokritische Partei gegründet." },
  { id: "wrecking_ball", title: "Miley Cyrus veröffentlicht „Wrecking Ball“", year: 2013, image: "img/wrecking_ball.svg", fact: "Das Musikvideo, in dem sie auf einer Abrissbirne sitzt, stellte einen Aufrufrekord auf." },
  { id: "wm2014", title: "Deutschland wird Fußball-Weltmeister in Brasilien", year: 2014, image: "img/wm2014.svg", fact: "Mario Götze schoss im Finale gegen Argentinien das 1:0 – der vierte WM-Titel." },
  { id: "robin_williams", title: "Robin Williams stirbt", year: 2014, image: "img/robin_williams.svg", fact: "Der Schauspieler („Mrs. Doubtfire“, Stimme des Dschinni in „Aladdin“) starb mit 63 Jahren." },
  { id: "paris_klima", title: "Pariser Klimaabkommen", year: 2015, image: "img/paris_klima.svg", fact: "Fast alle Staaten der Welt einigten sich, die Erderwärmung deutlich unter 2 °C zu halten." },
  { id: "brexit", title: "Brexit-Abstimmung in Großbritannien", year: 2016, image: "img/brexit.svg", fact: "Knapp 52 % stimmten für den Austritt aus der EU, der 2020 vollzogen wurde." },
  { id: "trump", title: "Donald Trump wird US-Präsident", year: 2017, image: "img/trump.svg", fact: "Der Unternehmer und frühere TV-Star trat im Januar 2017 sein Amt als 45. Präsident der USA an." },
  { id: "metoo", title: "Die #MeToo-Bewegung", year: 2017, image: "img/metoo.svg", fact: "Nach Berichten über Harvey Weinstein teilten Millionen Frauen unter #MeToo ihre Erfahrungen mit sexueller Belästigung." },
  { id: "neymar", title: "Neymar wechselt für 222 Mio. € zu Paris", year: 2017, image: "img/neymar.svg", fact: "Paris Saint-Germain zahlte dem FC Barcelona die höchste Ablösesumme der Fußballgeschichte." },
  { id: "greta", title: "Greta Thunbergs Schulstreik fürs Klima", year: 2018, image: "img/greta.svg", fact: "Daraus entstand die weltweite Bewegung „Fridays for Future“." },
  { id: "schwarzes_loch", title: "Erstes Foto eines Schwarzen Lochs", year: 2019, image: "img/schwarzes_loch.svg", fact: "Acht Radioteleskope rund um die Welt arbeiteten dafür wie ein einziges, erdgroßes Teleskop zusammen." },
  { id: "epstein", title: "Jeffrey Epstein wird festgenommen", year: 2019, image: "img/epstein.svg", fact: "Der US-Multimillionär wurde wegen Menschenhandels mit Minderjährigen angeklagt und starb wenige Wochen später in Haft." },
  { id: "corona", title: "Corona-Pandemie", year: 2020, image: "img/corona.svg", fact: "Die WHO erklärte COVID-19 im März 2020 zur Pandemie." },
  { id: "webb", title: "Start des James-Webb-Weltraumteleskops", year: 2021, image: "img/webb.svg", fact: "Sein goldener Spiegel aus 18 Segmenten blickt bis kurz nach dem Urknall zurück." },
  { id: "chatgpt", title: "KI-Chatbot ChatGPT wird veröffentlicht", year: 2022, image: "img/chatgpt.svg", fact: "Innerhalb von zwei Monaten nutzten ihn rund 100 Millionen Menschen." },
  { id: "ukraine", title: "Russland greift die Ukraine an", year: 2022, image: "img/ukraine.svg", fact: "Am 24. Februar begann der russische Großangriff auf das ganze Land." },
  { id: "will_smith", title: "Will Smiths Ohrfeige bei den Oscars", year: 2022, image: "img/will_smith.svg", fact: "Will Smith ohrfeigte auf der Bühne den Moderator Chris Rock – kurz darauf gewann er den Oscar als bester Hauptdarsteller." },
  { id: "messi", title: "Messi wird mit Argentinien Weltmeister", year: 2022, image: "img/messi.svg", fact: "Im Finale in Katar besiegte Argentinien Frankreich nach einem 3:3 im Elfmeterschießen." },
  { id: "atomausstieg", title: "Deutschland schaltet die letzten Atomkraftwerke ab", year: 2023, image: "img/atomausstieg.svg", fact: "Am 15. April 2023 gingen die drei letzten deutschen Kernkraftwerke vom Netz." },
  { id: "olympia_paris", title: "Olympische Sommerspiele in Paris", year: 2024, image: "img/olympia_paris.svg", fact: "Die Eröffnungsfeier fand erstmals nicht in einem Stadion statt, sondern auf der Seine." },
  { id: "papst", title: "Leo XIV. – erster Papst aus den USA", year: 2025, image: "img/papst.svg", fact: "Der in Chicago geborene Robert Francis Prevost wurde im Mai 2025 zum Papst gewählt." },
  { id: "wm2026", title: "Erste Fußball-WM mit 48 Mannschaften", year: 2026, image: "img/wm2026.svg", fact: "Das Turnier wurde erstmals in drei Ländern ausgetragen: USA, Kanada und Mexiko." },
];
