// Ereignisse der Menschheitsgeschichte.
// year: negative Zahlen = v. Chr.  |  approx: true = Jahr ist eine Schätzung ("ca.")
// image: Pfad zum Bild (SVG, WebP, JPG ... – max. ~50 KB pro Bild empfohlen)
const EVENTS = [
  { id: "lascaux", title: "Höhlenmalereien von Lascaux", year: -17000, approx: true, image: "img/lascaux.svg", fact: "Steinzeitliche Menschen malten Tiere wie Pferde und Stiere an die Wände der Höhle in Südfrankreich." },
  { id: "landwirtschaft", title: "Beginn des Ackerbaus", year: -10000, approx: true, image: "img/landwirtschaft.svg", fact: "Im „Fruchtbaren Halbmond“ wurden Menschen sesshaft und bauten Getreide an (Neolithische Revolution)." },
  { id: "rad", title: "Erfindung des Rades", year: -3500, approx: true, image: "img/rad.svg", fact: "Die ältesten Räder stammen aus Mesopotamien und Europa – zuerst wohl als Töpferscheibe." },
  { id: "schrift", title: "Erfindung der Keilschrift", year: -3200, approx: true, image: "img/schrift.svg", fact: "Die Sumerer drückten Zeichen mit einem Griffel in feuchte Tontafeln." },
  { id: "pyramide", title: "Bau der Cheops-Pyramide", year: -2560, approx: true, image: "img/pyramide.svg", fact: "Die Große Pyramide von Gizeh war fast 4.000 Jahre lang das höchste Bauwerk der Welt." },
  { id: "hammurabi", title: "Codex Hammurabi", year: -1754, approx: true, image: "img/hammurabi.svg", fact: "Eine der ältesten erhaltenen Gesetzessammlungen – in eine Steinstele gemeißelt." },
  { id: "olympia", title: "Erste Olympische Spiele der Antike", year: -776, image: "img/olympia.svg", fact: "Die Spiele in Olympia wurden zu Ehren des Zeus abgehalten." },
  { id: "rom", title: "Gründung Roms (Sage)", year: -753, image: "img/rom.svg", fact: "Der Sage nach gründeten die Zwillinge Romulus und Remus die Stadt." },
  { id: "marathon", title: "Schlacht bei Marathon", year: -490, image: "img/marathon.svg", fact: "Die Athener besiegten die Perser – der Legende nach entstand daraus der Marathonlauf." },
  { id: "mauer_china", title: "Einigung Chinas & Bau der Großen Mauer", year: -221, image: "img/mauer_china.svg", fact: "Kaiser Qin Shi Huang ließ ältere Mauerstücke zu einem Bollwerk verbinden." },
  { id: "caesar", title: "Ermordung Julius Caesars", year: -44, image: "img/caesar.svg", fact: "Caesar wurde an den Iden des März im römischen Senat erstochen." },
  { id: "vesuv", title: "Vesuv-Ausbruch zerstört Pompeji", year: 79, image: "img/vesuv.svg", fact: "Die Asche konservierte die Stadt so gut, dass man sie heute noch besichtigen kann." },
  { id: "westrom", title: "Ende des Weströmischen Reiches", year: 476, image: "img/westrom.svg", fact: "Der Germane Odoaker setzte den letzten weströmischen Kaiser Romulus Augustulus ab." },
  { id: "hidschra", title: "Hidschra – Beginn der islamischen Zeitrechnung", year: 622, image: "img/hidschra.svg", fact: "Mohammed zog von Mekka nach Medina; mit diesem Jahr beginnt der islamische Kalender." },
  { id: "karl", title: "Kaiserkrönung Karls des Großen", year: 800, image: "img/karl.svg", fact: "Papst Leo III. krönte Karl am Weihnachtstag in Rom zum Kaiser." },
  { id: "hastings", title: "Schlacht bei Hastings", year: 1066, image: "img/hastings.svg", fact: "Wilhelm der Eroberer besiegte die Angelsachsen und wurde König von England." },
  { id: "kreuzzug", title: "Beginn des Ersten Kreuzzugs", year: 1096, image: "img/kreuzzug.svg", fact: "Papst Urban II. rief zur Eroberung Jerusalems auf." },
  { id: "magna_carta", title: "Magna Carta", year: 1215, image: "img/magna_carta.svg", fact: "Der englische König Johann Ohneland musste die Rechte des Adels schriftlich anerkennen." },
  { id: "pest", title: "Der „Schwarze Tod“ erreicht Europa", year: 1347, image: "img/pest.svg", fact: "Die Pest tötete in wenigen Jahren etwa ein Drittel der Bevölkerung Europas." },
  { id: "buchdruck", title: "Gutenberg erfindet den Buchdruck", year: 1450, approx: true, image: "img/buchdruck.svg", fact: "Mit beweglichen Metalllettern konnten Bücher erstmals schnell vervielfältigt werden." },
  { id: "kolumbus", title: "Kolumbus erreicht Amerika", year: 1492, image: "img/kolumbus.svg", fact: "Eigentlich wollte Kolumbus einen westlichen Seeweg nach Indien finden." },
  { id: "mona_lisa", title: "Leonardo beginnt die Mona Lisa", year: 1503, image: "img/mona_lisa.svg", fact: "Das Gemälde hängt heute im Louvre in Paris." },
  { id: "luther", title: "Luthers 95 Thesen – Reformation", year: 1517, image: "img/luther.svg", fact: "Martin Luther kritisierte den Ablasshandel der Kirche." },
  { id: "magellan", title: "Magellans Weltumsegelung beginnt", year: 1519, image: "img/magellan.svg", fact: "Die erste Umrundung der Erde dauerte drei Jahre – Magellan selbst überlebte sie nicht." },
  { id: "kopernikus", title: "Kopernikus: Die Erde kreist um die Sonne", year: 1543, image: "img/kopernikus.svg", fact: "Sein heliozentrisches Weltbild stellte die Sonne in den Mittelpunkt." },
  { id: "dreissig", title: "Beginn des Dreißigjährigen Krieges", year: 1618, image: "img/dreissig.svg", fact: "Ausgelöst wurde er durch den Prager Fenstersturz." },
  { id: "newton", title: "Newton veröffentlicht das Gravitationsgesetz", year: 1687, image: "img/newton.svg", fact: "In seinem Werk „Principia“ beschrieb Newton die Gesetze der Bewegung und Schwerkraft." },
  { id: "dampfmaschine", title: "James Watts verbesserte Dampfmaschine", year: 1769, image: "img/dampfmaschine.svg", fact: "Sie wurde zum Motor der Industriellen Revolution." },
  { id: "usa", title: "Unabhängigkeitserklärung der USA", year: 1776, image: "img/usa.svg", fact: "Am 4. Juli sagten sich 13 Kolonien von Großbritannien los." },
  { id: "franz_revolution", title: "Französische Revolution – Sturm auf die Bastille", year: 1789, image: "img/franz_revolution.svg", fact: "„Freiheit, Gleichheit, Brüderlichkeit“ wurde zum Leitspruch." },
  { id: "waterloo", title: "Napoleons Niederlage bei Waterloo", year: 1815, image: "img/waterloo.svg", fact: "Danach wurde Napoleon auf die Insel St. Helena verbannt." },
  { id: "eisenbahn", title: "Erste Eisenbahn in Deutschland", year: 1835, image: "img/eisenbahn.svg", fact: "Der „Adler“ fuhr von Nürnberg nach Fürth." },
  { id: "darwin", title: "Darwins Evolutionstheorie", year: 1859, image: "img/darwin.svg", fact: "In „Über die Entstehung der Arten“ erklärte Darwin die natürliche Auslese." },
  { id: "kaiserreich", title: "Gründung des Deutschen Kaiserreichs", year: 1871, image: "img/kaiserreich.svg", fact: "Wilhelm I. wurde im Spiegelsaal von Versailles zum Kaiser ausgerufen." },
  { id: "telefon", title: "Erfindung des Telefons", year: 1876, image: "img/telefon.svg", fact: "Alexander Graham Bell meldete das Patent an – Philipp Reis hatte schon vorher ein Gerät gebaut." },
  { id: "gluehbirne", title: "Edisons Glühbirne", year: 1879, image: "img/gluehbirne.svg", fact: "Edison entwickelte eine langlebige Glühlampe mit Kohlefaden." },
  { id: "automobil", title: "Benz baut das erste Automobil", year: 1886, image: "img/automobil.svg", fact: "Der Benz Patent-Motorwagen Nummer 1 hatte drei Räder." },
  { id: "roentgen", title: "Röntgen entdeckt die X-Strahlen", year: 1895, image: "img/roentgen.svg", fact: "Das erste Röntgenbild zeigte die Hand seiner Frau – mit Ehering." },
  { id: "motorflug", title: "Erster Motorflug der Brüder Wright", year: 1903, image: "img/motorflug.svg", fact: "Der erste Flug dauerte nur 12 Sekunden und war 37 Meter lang." },
  { id: "titanic", title: "Untergang der Titanic", year: 1912, image: "img/titanic.svg", fact: "Das „unsinkbare“ Schiff kollidierte auf seiner Jungfernfahrt mit einem Eisberg." },
  { id: "wk1", title: "Beginn des Ersten Weltkriegs", year: 1914, image: "img/wk1.svg", fact: "Auslöser war das Attentat von Sarajevo auf den österreichischen Thronfolger." },
  { id: "penicillin", title: "Entdeckung des Penicillins", year: 1928, image: "img/penicillin.svg", fact: "Alexander Fleming bemerkte, dass ein Schimmelpilz Bakterien abtötet." },
  { id: "wk2", title: "Beginn des Zweiten Weltkriegs", year: 1939, image: "img/wk2.svg", fact: "Am 1. September überfiel Deutschland Polen." },
  { id: "hiroshima", title: "Atombombenabwurf auf Hiroshima", year: 1945, image: "img/hiroshima.svg", fact: "Der erste Einsatz einer Atomwaffe im Krieg; kurz darauf folgte Nagasaki." },
  { id: "menschenrechte", title: "Allgemeine Erklärung der Menschenrechte", year: 1948, image: "img/menschenrechte.svg", fact: "Die Vereinten Nationen verabschiedeten sie am 10. Dezember." },
  { id: "dna", title: "Entdeckung der DNA-Doppelhelix", year: 1953, image: "img/dna.svg", fact: "Watson und Crick beschrieben die Struktur – mit Hilfe von Rosalind Franklins Röntgenbildern." },
  { id: "sputnik", title: "Sputnik – erster künstlicher Satellit", year: 1957, image: "img/sputnik.svg", fact: "Der sowjetische Satellit löste den „Wettlauf ins All“ aus." },
  { id: "mauerbau", title: "Bau der Berliner Mauer", year: 1961, image: "img/mauerbau.svg", fact: "Die DDR riegelte am 13. August West-Berlin ab." },
  { id: "mondlandung", title: "Erste Mondlandung", year: 1969, image: "img/mondlandung.svg", fact: "Neil Armstrong betrat als erster Mensch den Mond." },
  { id: "pc", title: "Der IBM Personal Computer erscheint", year: 1981, image: "img/pc.svg", fact: "Der „IBM PC“ machte den Computer zum Bürogerät." },
  { id: "mauerfall", title: "Fall der Berliner Mauer", year: 1989, image: "img/mauerfall.svg", fact: "Am 9. November öffnete die DDR die Grenzübergänge." },
  { id: "wiedervereinigung", title: "Deutsche Wiedervereinigung", year: 1990, image: "img/wiedervereinigung.svg", fact: "Am 3. Oktober trat die DDR der Bundesrepublik bei." },
  { id: "www", title: "Das World Wide Web geht online", year: 1991, image: "img/www.svg", fact: "Tim Berners-Lee entwickelte das WWW am Forschungszentrum CERN." },
  { id: "dolly", title: "Klonschaf Dolly wird geboren", year: 1996, image: "img/dolly.svg", fact: "Dolly war das erste aus einer erwachsenen Körperzelle geklonte Säugetier." },
  { id: "euro", title: "Euro-Bargeld wird eingeführt", year: 2002, image: "img/euro.svg", fact: "Am 1. Januar löste der Euro u. a. die D-Mark ab." },
  { id: "smartphone", title: "Das erste iPhone wird vorgestellt", year: 2007, image: "img/smartphone.svg", fact: "Es machte Touchscreen-Smartphones massentauglich." },
  { id: "corona", title: "Corona-Pandemie", year: 2020, image: "img/corona.svg", fact: "Die WHO erklärte COVID-19 im März 2020 zur Pandemie." },
];
