// Ereignisse der Menschheitsgeschichte.
// year: negative Zahlen = v. Chr.  |  approx: true = Jahr ist eine Schätzung ("ca.")
// image: Pfad zum Bild (SVG, WebP, JPG ... – max. ~50 KB pro Bild empfohlen)
const EVENTS = [
  { id: "rad", title: "Erfindung des Rades", year: -3500, approx: true, image: "img/rad.svg", fact: "Die ältesten Räder stammen aus Mesopotamien und Europa – zuerst wohl als Töpferscheibe." },
  { id: "pyramide", title: "Bau der Cheops-Pyramide", year: -2560, approx: true, image: "img/pyramide.svg", fact: "Die Große Pyramide von Gizeh war fast 4.000 Jahre lang das höchste Bauwerk der Welt." },
  { id: "olympia", title: "Erste Olympische Spiele der Antike", year: -776, image: "img/olympia.svg", fact: "Die Spiele in Olympia wurden zu Ehren des Zeus abgehalten." },
  { id: "mauer_china", title: "Einigung Chinas & Bau der Großen Mauer", year: -221, image: "img/mauer_china.svg", fact: "Kaiser Qin Shi Huang ließ ältere Mauerstücke zu einem Bollwerk verbinden." },
  { id: "caesar", title: "Ermordung Julius Caesars", year: -44, image: "img/caesar.svg", fact: "Caesar wurde an den Iden des März im römischen Senat erstochen." },
  { id: "vesuv", title: "Vesuv-Ausbruch zerstört Pompeji", year: 79, image: "img/vesuv.svg", fact: "Die Asche konservierte die Stadt so gut, dass man sie heute noch besichtigen kann." },
  { id: "karl", title: "Kaiserkrönung Karls des Großen", year: 800, image: "img/karl.svg", fact: "Papst Leo III. krönte Karl am Weihnachtstag in Rom zum Kaiser." },
  { id: "augustiner", title: "Augustiner – die älteste Brauerei Münchens", year: 1328, image: "img/augustiner.svg", fact: "Mönche des Augustinerklosters brauten erstmals Bier – die Brauerei gibt es bis heute." },
  { id: "buchdruck", title: "Gutenberg erfindet den Buchdruck", year: 1450, approx: true, image: "img/buchdruck.svg", fact: "Mit beweglichen Metalllettern konnten Bücher erstmals schnell vervielfältigt werden." },
  { id: "kolumbus", title: "Kolumbus erreicht Amerika", year: 1492, image: "img/kolumbus.svg", fact: "Eigentlich wollte Kolumbus einen westlichen Seeweg nach Indien finden." },
  { id: "luther", title: "Luthers 95 Thesen – Reformation", year: 1517, image: "img/luther.svg", fact: "Martin Luther kritisierte den Ablasshandel der Kirche." },
  { id: "donquijote", title: "„Don Quijote“ wird veröffentlicht", year: 1605, image: "img/donquijote.svg", fact: "Miguel de Cervantes’ Ritter kämpft gegen Windmühlen, die er für Riesen hält – einer der ersten modernen Romane." },
  { id: "newton", title: "Newton veröffentlicht das Gravitationsgesetz", year: 1687, image: "img/newton.svg", fact: "In seinem Werk „Principia“ beschrieb Newton die Gesetze der Bewegung und Schwerkraft." },
  { id: "franklin", title: "Benjamin Franklins Drachenexperiment", year: 1752, image: "img/franklin.svg", fact: "Franklin bewies mit einem Drachen im Gewitter, dass Blitze elektrisch sind – und erfand den Blitzableiter." },
  { id: "mozart", title: "Wolfgang Amadeus Mozart wird geboren", year: 1756, image: "img/mozart.svg", fact: "Das Wunderkind aus Salzburg komponierte schon mit fünf Jahren seine ersten Stücke." },
  { id: "dampfmaschine", title: "James Watts verbesserte Dampfmaschine", year: 1769, image: "img/dampfmaschine.svg", fact: "Sie wurde zum Motor der Industriellen Revolution." },
  { id: "usa", title: "Unabhängigkeitserklärung der USA", year: 1776, image: "img/usa.svg", fact: "Am 4. Juli sagten sich 13 Kolonien von Großbritannien los." },
  { id: "ballon", title: "Erster bemannter Flug im Heißluftballon", year: 1783, image: "img/ballon.svg", fact: "Ein Ballon der Brüder Montgolfier trug in Paris erstmals Menschen in die Luft." },
  { id: "franz_revolution", title: "Französische Revolution – Sturm auf die Bastille", year: 1789, image: "img/franz_revolution.svg", fact: "„Freiheit, Gleichheit, Brüderlichkeit“ wurde zum Leitspruch." },
  { id: "brandenburger_tor", title: "Das Brandenburger Tor wird fertiggestellt", year: 1791, image: "img/brandenburger_tor.svg", fact: "Das Wahrzeichen Berlins stand später jahrzehntelang direkt an der Berliner Mauer." },
  { id: "impfung", title: "Edward Jenner erfindet die Pockenimpfung", year: 1796, image: "img/impfung.svg", fact: "Er nutzte harmlose Kuhpocken – daher kommt das Wort „Vakzin“ (lateinisch vacca = Kuh)." },
  { id: "napoleon", title: "Napoleon krönt sich selbst zum Kaiser", year: 1804, image: "img/napoleon.svg", fact: "In der Kathedrale Notre-Dame nahm er dem Papst die Krone ab und setzte sie sich selbst auf." },
  { id: "oktoberfest1810", title: "Das erste Oktoberfest", year: 1810, image: "img/oktoberfest1810.svg", fact: "Anlass war die Hochzeit von Kronprinz Ludwig und Therese – gefeiert wurde mit einem Pferderennen auf der heutigen Theresienwiese." },
  { id: "grimm", title: "Die Brüder Grimm veröffentlichen ihre Märchen", year: 1812, image: "img/grimm.svg", fact: "Der erste Band der „Kinder- und Hausmärchen“ enthielt u. a. Rotkäppchen und Hänsel und Gretel." },
  { id: "draisine", title: "Karl Drais erfindet die Laufmaschine", year: 1817, image: "img/draisine.svg", fact: "Die „Draisine“ aus Mannheim hatte noch keine Pedale – sie gilt als Urahn des Fahrrads." },
  { id: "brasilien", title: "Brasilien wird unabhängig", year: 1822, image: "img/brasilien.svg", fact: "Kronprinz Pedro erklärte die Unabhängigkeit von Portugal und wurde Kaiser von Brasilien." },
  { id: "beethoven9", title: "Uraufführung von Beethovens 9. Sinfonie", year: 1824, image: "img/beethoven9.svg", fact: "Beethoven war bereits taub; die „Ode an die Freude“ ist heute die Hymne der EU." },
  { id: "erstes_foto", title: "Das erste erhaltene Foto der Welt", year: 1826, approx: true, image: "img/erstes_foto.svg", fact: "Joseph Nicéphore Niépce fotografierte den Blick aus seinem Fenster – die Belichtung dauerte Stunden." },
  { id: "eisenbahn", title: "Erste Eisenbahn in Deutschland", year: 1835, image: "img/eisenbahn.svg", fact: "Der „Adler“ fuhr von Nürnberg nach Fürth." },
  { id: "ca", title: "Gründung von C&A", year: 1841, image: "img/ca.svg", fact: "Die Brüder Clemens und August Brenninkmeyer eröffneten ihr erstes Geschäft im niederländischen Sneek." },
  { id: "zoo_berlin", title: "Der erste Zoo Deutschlands eröffnet in Berlin", year: 1844, image: "img/zoo_berlin.svg", fact: "Der Zoologische Garten Berlin ist heute einer der artenreichsten Zoos der Welt." },
  { id: "siemens", title: "Gründung von Siemens", year: 1847, image: "img/siemens.svg", fact: "Werner von Siemens und Johann Georg Halske gründeten in Berlin eine Firma für Zeigertelegrafen." },
  { id: "manifest", title: "Das „Kommunistische Manifest“ erscheint", year: 1848, image: "img/manifest.svg", fact: "Karl Marx und Friedrich Engels riefen: „Proletarier aller Länder, vereinigt euch!“" },
  { id: "paulskirche", title: "Die Nationalversammlung tagt in der Paulskirche", year: 1848, image: "img/paulskirche.svg", fact: "In Frankfurt trat das erste frei gewählte gesamtdeutsche Parlament zusammen." },
  { id: "darwin", title: "Darwins Evolutionstheorie", year: 1859, image: "img/darwin.svg", fact: "In „Über die Entstehung der Arten“ erklärte Darwin die natürliche Auslese." },
  { id: "bayer", title: "Gründung von Bayer", year: 1863, image: "img/bayer.svg", fact: "Friedrich Bayer gründete in Barmen eine Farbenfabrik – später wurde Bayer mit Aspirin weltberühmt." },
  { id: "buergerkrieg_usa", title: "Ende des Amerikanischen Bürgerkriegs", year: 1865, image: "img/buergerkrieg_usa.svg", fact: "Die Nordstaaten siegten über die Südstaaten – die Sklaverei wurde in den USA abgeschafft." },
  { id: "nokia", title: "Gründung von Nokia", year: 1865, image: "img/nokia.svg", fact: "Das finnische Unternehmen begann als Papierfabrik – Handys kamen erst über 100 Jahre später." },
  { id: "dynamit", title: "Alfred Nobel erfindet das Dynamit", year: 1867, image: "img/dynamit.svg", fact: "Mit seinem Vermögen stiftete Nobel später die Nobelpreise." },
  { id: "suezkanal", title: "Der Suezkanal wird eröffnet", year: 1869, image: "img/suezkanal.svg", fact: "Schiffe zwischen Europa und Asien mussten nun nicht mehr um ganz Afrika herumfahren." },
  { id: "telefon", title: "Erfindung des Telefons", year: 1876, image: "img/telefon.svg", fact: "Alexander Graham Bell meldete das Patent an – Philipp Reis hatte schon vorher ein Gerät gebaut." },
  { id: "gluehbirne", title: "Edisons Glühbirne", year: 1879, image: "img/gluehbirne.svg", fact: "Edison entwickelte eine langlebige Glühlampe mit Kohlefaden." },
  { id: "koch_tbc", title: "Robert Koch entdeckt den Tuberkulose-Erreger", year: 1882, image: "img/koch_tbc.svg", fact: "Für diese Entdeckung bekam er später den Nobelpreis – der 24. März ist heute Welttuberkulosetag." },
  { id: "kongokonferenz", title: "Berliner Kongokonferenz", year: 1884, image: "img/kongokonferenz.svg", fact: "Europäische Mächte legten in Berlin Regeln für die Aufteilung Afrikas fest – ohne Afrikaner zu fragen." },
  { id: "automobil", title: "Benz baut das erste Automobil", year: 1886, image: "img/automobil.svg", fact: "Der Benz Patent-Motorwagen Nummer 1 hatte drei Räder." },
  { id: "freiheitsstatue", title: "Die Freiheitsstatue wird eingeweiht", year: 1886, image: "img/freiheitsstatue.svg", fact: "Die Statue war ein Geschenk Frankreichs an die USA und steht im Hafen von New York." },
  { id: "cocacola", title: "Coca-Cola wird erfunden", year: 1886, image: "img/cocacola.svg", fact: "Der Apotheker John Pemberton aus Atlanta verkaufte das Getränk zuerst als Medizin." },
  { id: "hsv", title: "Gründung des Hamburger SV", year: 1887, image: "img/hsv.svg", fact: "Der HSV führt seine Geschichte auf den SC Germania von 1887 zurück und ist einer der ältesten Fußballvereine Deutschlands." },
  { id: "jack_ripper", title: "Erster Mord von Jack the Ripper", year: 1888, image: "img/jack_ripper.svg", fact: "Der Serienmörder schlug im Londoner Stadtteil Whitechapel zu – seine Identität ist bis heute ungeklärt." },
  { id: "eiffelturm", title: "Der Eiffelturm wird eingeweiht", year: 1889, image: "img/eiffelturm.svg", fact: "Er wurde für die Weltausstellung in Paris gebaut und sollte eigentlich nach 20 Jahren wieder abgerissen werden." },
  { id: "roentgen", title: "Röntgen entdeckt die X-Strahlen", year: 1895, image: "img/roentgen.svg", fact: "Das erste Röntgenbild zeigte die Hand seiner Frau – mit Ehering." },
  { id: "kino_lumiere", title: "Die erste öffentliche Kinovorführung", year: 1895, image: "img/kino_lumiere.svg", fact: "Die Brüder Lumière zeigten in einem Pariser Café kurze Filme gegen Eintritt." },
  { id: "olympia1896", title: "Erste Olympische Spiele der Neuzeit", year: 1896, image: "img/olympia1896.svg", fact: "Sie fanden in Athen statt – auf Initiative des Franzosen Pierre de Coubertin." },
  { id: "edeka", title: "Gründung von Edeka", year: 1898, image: "img/edeka.svg", fact: "Kaufleute in Berlin schlossen sich zur „Einkaufsgenossenschaft der Kolonialwarenhändler“ zusammen – kurz E. d. K." },
  { id: "aspirin", title: "Aspirin kommt auf den Markt", year: 1899, image: "img/aspirin.svg", fact: "Bayer ließ den Namen schützen – Aspirin wurde eines der meistverkauften Medikamente der Welt." },
  { id: "gladbach", title: "Gründung von Borussia Mönchengladbach", year: 1900, image: "img/gladbach.svg", fact: "Die „Fohlen“ wurden in den 1970er-Jahren fünfmal Deutscher Meister." },
  { id: "marconi", title: "Erste Funkübertragung über den Atlantik", year: 1901, image: "img/marconi.svg", fact: "Guglielmo Marconi empfing in Neufundland ein Funksignal aus England – ganz ohne Kabel." },
  { id: "nobelpreis", title: "Die ersten Nobelpreise werden verliehen", year: 1901, image: "img/nobelpreis.svg", fact: "Der erste Physik-Nobelpreis ging an Wilhelm Conrad Röntgen." },
  { id: "motorflug", title: "Erster Motorflug der Brüder Wright", year: 1903, image: "img/motorflug.svg", fact: "Der erste Flug dauerte nur 12 Sekunden und war 37 Meter lang." },
  { id: "adac", title: "Gründung des ADAC", year: 1903, image: "img/adac.svg", fact: "Der Club wurde in Stuttgart als „Deutsche Motorradfahrer-Vereinigung“ gegründet und heißt seit 1911 ADAC." },
  { id: "ubahn_ny", title: "Die New Yorker U-Bahn wird eröffnet", year: 1904, image: "img/ubahn_ny.svg", fact: "Heute ist die New York City Subway eines der größten U-Bahn-Netze der Welt." },
  { id: "einstein", title: "Einsteins Relativitätstheorie", year: 1905, image: "img/einstein.svg", fact: "Mit der berühmten Formel E = mc² zeigte Einstein, dass Masse und Energie zusammenhängen." },
  { id: "rolex", title: "Der Name „Rolex“ wird eingetragen", year: 1908, image: "img/rolex.svg", fact: "Hans Wilsdorf ließ den Markennamen schützen – er sollte in jeder Sprache leicht auszusprechen sein." },
  { id: "audi", title: "Gründung von Audi", year: 1909, image: "img/audi.svg", fact: "August Horch gründete eine neue Autofirma – „Audi“ ist die lateinische Übersetzung von „Horch!“." },
  { id: "amundsen", title: "Roald Amundsen erreicht den Südpol", year: 1911, image: "img/amundsen.svg", fact: "Der Norweger kam fünf Wochen vor seinem britischen Konkurrenten Robert Scott an." },
  { id: "titanic", title: "Untergang der Titanic", year: 1912, image: "img/titanic.svg", fact: "Das „unsinkbare“ Schiff kollidierte auf seiner Jungfernfahrt mit einem Eisberg." },
  { id: "fliessband", title: "Henry Ford führt das Fließband ein", year: 1913, image: "img/fliessband.svg", fact: "Statt rund 12 Stunden dauerte der Bau eines Ford Modell T nur noch etwa 1,5 Stunden." },
  { id: "wk1", title: "Beginn des Ersten Weltkriegs", year: 1914, image: "img/wk1.svg", fact: "Auslöser war das Attentat von Sarajevo auf den österreichischen Thronfolger." },
  { id: "kafka", title: "Kafkas „Die Verwandlung“ erscheint", year: 1915, image: "img/kafka.svg", fact: "Gregor Samsa erwacht eines Morgens als riesiges Ungeziefer." },
  { id: "oktoberrevolution", title: "Oktoberrevolution in Russland", year: 1917, image: "img/oktoberrevolution.svg", fact: "Die Bolschewiki unter Lenin übernahmen die Macht – später entstand daraus die Sowjetunion." },
  { id: "frauenwahlrecht", title: "Frauenwahlrecht in Deutschland", year: 1918, image: "img/frauenwahlrecht.svg", fact: "Im Januar 1919 durften Frauen zum ersten Mal in Deutschland wählen und gewählt werden." },
  { id: "versailles", title: "Versailler Vertrag", year: 1919, image: "img/versailles.svg", fact: "Der Friedensvertrag nach dem Ersten Weltkrieg legte Deutschland harte Bedingungen auf." },
  { id: "prohibition", title: "Beginn der Prohibition in den USA", year: 1920, image: "img/prohibition.svg", fact: "Alkohol war 13 Jahre lang verboten – davon profitierten vor allem Gangster wie Al Capone." },
  { id: "insulin", title: "Entdeckung des Insulins", year: 1921, image: "img/insulin.svg", fact: "Frederick Banting und Charles Best gelang es in Toronto, Insulin zu gewinnen – Diabetes wurde behandelbar." },
  { id: "tutanchamun", title: "Entdeckung des Grabes von Tutanchamun", year: 1922, image: "img/tutanchamun.svg", fact: "Howard Carter fand im Tal der Könige das fast unberührte Grab des jungen Pharaos." },
  { id: "mussolini", title: "Mussolini kommt in Italien an die Macht", year: 1922, image: "img/mussolini.svg", fact: "Nach dem „Marsch auf Rom“ wurde der Faschist Benito Mussolini Ministerpräsident." },
  { id: "hyperinflation", title: "Hyperinflation in Deutschland", year: 1923, image: "img/hyperinflation.svg", fact: "Das Geld verlor so schnell an Wert, dass ein Brot im Herbst Milliarden Mark kostete." },
  { id: "hitlerputsch", title: "Hitlerputsch in München", year: 1923, image: "img/hitlerputsch.svg", fact: "Der Umsturzversuch scheiterte; in der Haft schrieb Hitler „Mein Kampf“." },
  { id: "lenin", title: "Lenin stirbt", year: 1924, image: "img/lenin.svg", fact: "Der Gründer der Sowjetunion wurde einbalsamiert und liegt bis heute in einem Mausoleum in Moskau." },
  { id: "gatsby", title: "„Der große Gatsby“ erscheint", year: 1925, image: "img/gatsby.svg", fact: "F. Scott Fitzgeralds Roman über Partys, Reichtum und unerfüllte Liebe in den „Goldenen Zwanzigern“." },
  { id: "fernsehen", title: "Erste öffentliche Vorführung des Fernsehens", year: 1926, image: "img/fernsehen.svg", fact: "Der Schotte John Logie Baird zeigte in London die ersten bewegten Fernsehbilder." },
  { id: "lindbergh", title: "Lindbergh fliegt allein über den Atlantik", year: 1927, image: "img/lindbergh.svg", fact: "Charles Lindbergh flog in 33,5 Stunden ohne Zwischenstopp von New York nach Paris." },
  { id: "rewe", title: "Gründung von Rewe", year: 1927, image: "img/rewe.svg", fact: "Lebensmittelhändler in Köln gründeten die Einkaufsgenossenschaft – der Name steht für „Revisionsverband der Westkauf-Genossenschaften“." },
  { id: "penicillin", title: "Entdeckung des Penicillins", year: 1928, image: "img/penicillin.svg", fact: "Alexander Fleming bemerkte, dass ein Schimmelpilz Bakterien abtötet." },
  { id: "mickey", title: "Micky Maus feiert ihren Durchbruch", year: 1928, image: "img/mickey.svg", fact: "„Steamboat Willie“ war einer der ersten Zeichentrickfilme mit Ton." },
  { id: "boersencrash", title: "Börsencrash in New York", year: 1929, image: "img/boersencrash.svg", fact: "Der „Schwarze Donnerstag“ löste die Weltwirtschaftskrise aus." },
  { id: "timstruppi", title: "Das erste „Tim und Struppi“-Comic erscheint", year: 1929, image: "img/timstruppi.svg", fact: "Der Belgier Hergé schickte den Reporter Tim und seinen Hund Struppi zuerst ins „Land der Sowjets“." },
  { id: "oscars", title: "Die erste Oscar-Verleihung", year: 1929, image: "img/oscars.svg", fact: "Die Zeremonie in Hollywood dauerte nur 15 Minuten – die Gewinner standen schon vorher fest." },
  { id: "pluto", title: "Entdeckung des Pluto", year: 1930, image: "img/pluto.svg", fact: "Clyde Tombaugh entdeckte ihn – seit 2006 gilt Pluto nur noch als Zwergplanet." },
  { id: "wm1930", title: "Die erste Fußball-WM beginnt", year: 1930, image: "img/wm1930.svg", fact: "Gastgeber Uruguay wurde auch der erste Weltmeister – Deutschland nahm nicht teil." },
  { id: "empire_state", title: "Das Empire State Building wird eröffnet", year: 1931, image: "img/empire_state.svg", fact: "Mit 381 Metern war es rund 40 Jahre lang das höchste Gebäude der Welt." },
  { id: "reichstagsbrand", title: "Reichstagsbrand in Berlin", year: 1933, image: "img/reichstagsbrand.svg", fact: "Die Nationalsozialisten nutzten den Brand, um wichtige Grundrechte abzuschaffen." },
  { id: "spanischer_bk", title: "Ausbruch des Spanischen Bürgerkriegs", year: 1936, image: "img/spanischer_bk.svg", fact: "General Franco putschte gegen die Republik; nach drei Jahren Krieg errichtete er eine Diktatur." },
  { id: "olympia1936", title: "Olympische Spiele in Berlin", year: 1936, image: "img/olympia1936.svg", fact: "Die Nazis nutzten die Spiele zur Propaganda – Star wurde der schwarze US-Sprinter Jesse Owens mit vier Goldmedaillen." },
  { id: "hindenburg", title: "Absturz des Luftschiffs „Hindenburg“", year: 1937, image: "img/hindenburg.svg", fact: "Das Unglück in Lakehurst (USA) beendete das Zeitalter der großen Passagier-Luftschiffe." },
  { id: "vw_gruendung", title: "Gründung von Volkswagen", year: 1937, image: "img/vw_gruendung.svg", fact: "Das Unternehmen sollte ein günstiges „Auto für das Volk“ bauen – daraus wurde der VW Käfer." },
  { id: "kernspaltung", title: "Entdeckung der Kernspaltung", year: 1938, image: "img/kernspaltung.svg", fact: "Otto Hahn und Fritz Straßmann spalteten Uran; Lise Meitner lieferte die Erklärung." },
  { id: "superman", title: "Das erste Superman-Comic erscheint", year: 1938, image: "img/superman.svg", fact: "Superman hatte seinen ersten Auftritt in „Action Comics #1“ – der Beginn des Superhelden-Booms." },
  { id: "handball1938", title: "Deutschland wird erstmals Handball-Weltmeister", year: 1938, image: "img/handball1938.svg", fact: "Bei der ersten Hallenhandball-WM in Berlin gewann Deutschland alle Spiele." },
  { id: "pogrom", title: "Novemberpogrome", year: 1938, image: "img/pogrom.svg", fact: "In der Nacht vom 9. auf den 10. November zerstörten Nationalsozialisten Synagogen und jüdische Geschäfte in ganz Deutschland." },
  { id: "wk2", title: "Beginn des Zweiten Weltkriegs", year: 1939, image: "img/wk2.svg", fact: "Am 1. September überfiel Deutschland Polen." },
  { id: "zuse", title: "Konrad Zuse baut den ersten Computer (Z3)", year: 1941, image: "img/zuse.svg", fact: "Die Z3 gilt als erster funktionsfähiger, frei programmierbarer Rechner der Welt." },
  { id: "dday", title: "D-Day – Landung der Alliierten in der Normandie", year: 1944, image: "img/dday.svg", fact: "Mit der größten Landungsoperation der Geschichte begann die Befreiung Westeuropas." },
  { id: "hiroshima", title: "Atombombenabwurf auf Hiroshima", year: 1945, image: "img/hiroshima.svg", fact: "Der erste Einsatz einer Atomwaffe im Krieg; kurz darauf folgte Nagasaki." },
  { id: "un", title: "Gründung der Vereinten Nationen (UN)", year: 1945, image: "img/un.svg", fact: "Nach dem Zweiten Weltkrieg schlossen sich 51 Staaten zusammen, um den Frieden zu sichern." },
  { id: "auschwitz", title: "Befreiung des KZ Auschwitz", year: 1945, image: "img/auschwitz.svg", fact: "Am 27. Januar befreite die Rote Armee die Überlebenden – der Tag ist heute Holocaust-Gedenktag." },
  { id: "kriegsende", title: "Ende des Zweiten Weltkriegs in Europa", year: 1945, image: "img/kriegsende.svg", fact: "Am 8. Mai kapitulierte die deutsche Wehrmacht bedingungslos." },
  { id: "lucky_luke", title: "Lucky Luke erscheint zum ersten Mal", year: 1946, image: "img/lucky_luke.svg", fact: "Der Belgier Morris erfand den Cowboy, „der schneller zieht als sein Schatten“." },
  { id: "nba", title: "Die erste Saison der heutigen NBA startet", year: 1946, image: "img/nba.svg", fact: "Die Liga hieß zuerst BAA und bekam 1949 den Namen NBA." },
  { id: "indien", title: "Indien wird unabhängig", year: 1947, image: "img/indien.svg", fact: "Mahatma Gandhi hatte mit gewaltlosem Widerstand gegen die britische Herrschaft gekämpft." },
  { id: "hm", title: "Gründung von H&M", year: 1947, image: "img/hm.svg", fact: "Erling Persson eröffnete im schwedischen Västerås den Damenmodeladen „Hennes“ (schwedisch für „ihr“)." },
  { id: "preussen", title: "Preußen wird aufgelöst", year: 1947, image: "img/preussen.svg", fact: "Die Alliierten lösten den Staat Preußen per Kontrollratsgesetz offiziell auf." },
  { id: "menschenrechte", title: "Allgemeine Erklärung der Menschenrechte", year: 1948, image: "img/menschenrechte.svg", fact: "Die Vereinten Nationen verabschiedeten sie am 10. Dezember." },
  { id: "apartheid", title: "Beginn der Apartheid in Südafrika", year: 1948, image: "img/apartheid.svg", fact: "Die Regierung trennte Menschen gesetzlich nach Hautfarbe – Schwarze wurden massiv benachteiligt." },
  { id: "israel", title: "Gründung des Staates Israel", year: 1948, image: "img/israel.svg", fact: "David Ben-Gurion rief am 14. Mai in Tel Aviv den Staat Israel aus." },
  { id: "dmark", title: "Die D-Mark wird eingeführt", year: 1948, image: "img/dmark.svg", fact: "Mit der Währungsreform bekam jeder in den Westzonen 40 DM „Kopfgeld“ – die Läden füllten sich über Nacht." },
  { id: "luftbruecke", title: "Beginn der Berliner Luftbrücke", year: 1948, image: "img/luftbruecke.svg", fact: "Als die Sowjetunion West-Berlin blockierte, versorgten „Rosinenbomber“ die Stadt fast ein Jahr lang aus der Luft." },
  { id: "grundgesetz", title: "Das Grundgesetz – Gründung der Bundesrepublik", year: 1949, image: "img/grundgesetz.svg", fact: "Am 23. Mai 1949 trat die Verfassung der Bundesrepublik Deutschland in Kraft." },
  { id: "nato", title: "Gründung der NATO", year: 1949, image: "img/nato.svg", fact: "Zwölf Staaten aus Nordamerika und Europa gründeten in Washington ein Verteidigungsbündnis." },
  { id: "fdp", title: "Die FDP ist erstmals an der Bundesregierung beteiligt", year: 1949, image: "img/fdp.svg", fact: "Sie regierte im ersten Kabinett von Konrad Adenauer mit – Theodor Heuss von der FDP wurde Bundespräsident." },
  { id: "orwell1984", title: "Orwells Roman „1984“ erscheint", year: 1949, image: "img/orwell1984.svg", fact: "George Orwell beschrieb einen Überwachungsstaat – „Big Brother is watching you“." },
  { id: "peanuts", title: "Der Comic „Peanuts“ erscheint erstmals", year: 1950, image: "img/peanuts.svg", fact: "Charles M. Schulz zeichnete Charlie Brown und Snoopy fast 50 Jahre lang." },
  { id: "tagesschau", title: "Die Tagesschau läuft erstmals im Fernsehen", year: 1952, image: "img/tagesschau.svg", fact: "Am 26. Dezember 1952 sendete die ARD die erste Ausgabe." },
  { id: "dna", title: "Entdeckung der DNA-Doppelhelix", year: 1953, image: "img/dna.svg", fact: "Watson und Crick beschrieben die Struktur – mit Hilfe von Rosalind Franklins Röntgenbildern." },
  { id: "everest", title: "Erstbesteigung des Mount Everest", year: 1953, image: "img/everest.svg", fact: "Edmund Hillary und Tenzing Norgay standen als Erste auf dem höchsten Berg der Erde." },
  { id: "stalin", title: "Tod von Josef Stalin", year: 1953, image: "img/stalin.svg", fact: "Der sowjetische Diktator starb in Moskau; unter seiner Herrschaft wurden Millionen Menschen verfolgt." },
  { id: "juni1953", title: "Volksaufstand vom 17. Juni in der DDR", year: 1953, image: "img/juni1953.svg", fact: "Hunderttausende protestierten gegen die SED – sowjetische Panzer schlugen den Aufstand nieder." },
  { id: "bern", title: "„Das Wunder von Bern“", year: 1954, image: "img/bern.svg", fact: "Deutschland wurde mit einem 3:2 gegen Ungarn zum ersten Mal Fußball-Weltmeister." },
  { id: "rosa_parks", title: "Rosa Parks verweigert ihren Busplatz", year: 1955, image: "img/rosa_parks.svg", fact: "Sie weigerte sich in Montgomery (USA), ihren Sitz für einen Weißen zu räumen – der Auftakt eines großen Busboykotts." },
  { id: "disneyland", title: "Disneyland wird eröffnet", year: 1955, image: "img/disneyland.svg", fact: "Walt Disney eröffnete seinen ersten Freizeitpark in Anaheim, Kalifornien." },
  { id: "lufthansa", title: "Erster Flug der heutigen Lufthansa", year: 1955, image: "img/lufthansa.svg", fact: "Nach dem Krieg durfte Deutschland wieder Flugzeuge betreiben – am 1. April 1955 startete die neu gegründete Lufthansa." },
  { id: "sputnik", title: "Sputnik – erster künstlicher Satellit", year: 1957, image: "img/sputnik.svg", fact: "Der sowjetische Satellit löste den „Wettlauf ins All“ aus." },
  { id: "ghana", title: "Ghana wird unabhängig", year: 1957, image: "img/ghana.svg", fact: "Als eine der ersten Kolonien Afrikas löste sich Ghana von Großbritannien – erster Regierungschef wurde Kwame Nkrumah." },
  { id: "roemvertraege", title: "Die Römischen Verträge werden unterzeichnet", year: 1957, image: "img/roemvertraege.svg", fact: "Sechs Staaten gründeten die Europäische Wirtschaftsgemeinschaft – den Vorläufer der EU." },
  { id: "lego", title: "Der LEGO-Stein wird patentiert", year: 1958, image: "img/lego.svg", fact: "Die dänische Firma ließ den Noppenstein patentieren – er passt bis heute auf jeden alten Stein." },
  { id: "asterix", title: "Asterix erscheint zum ersten Mal", year: 1959, image: "img/asterix.svg", fact: "René Goscinny und Albert Uderzo veröffentlichten den Gallier erstmals im französischen Magazin „Pilote“." },
  { id: "barbie", title: "Die Barbie-Puppe kommt auf den Markt", year: 1959, image: "img/barbie.svg", fact: "Ruth Handler stellte die Puppe auf der Spielwarenmesse in New York vor." },
  { id: "pille", title: "Die Antibabypille kommt auf den Markt", year: 1960, image: "img/pille.svg", fact: "Zuerst in den USA zugelassen, ab 1961 auch in Deutschland erhältlich." },
  { id: "mauerbau", title: "Bau der Berliner Mauer", year: 1961, image: "img/mauerbau.svg", fact: "Die DDR riegelte am 13. August West-Berlin ab." },
  { id: "gagarin", title: "Juri Gagarin – erster Mensch im All", year: 1961, image: "img/gagarin.svg", fact: "Mit der Wostok 1 umrundete Gagarin in 108 Minuten einmal die Erde." },
  { id: "kubakrise", title: "Kubakrise", year: 1962, image: "img/kubakrise.svg", fact: "Sowjetische Atomraketen auf Kuba brachten die Welt 13 Tage lang an den Rand eines Atomkriegs." },
  { id: "beatles", title: "Die Beatles veröffentlichen ihre erste Single", year: 1962, image: "img/beatles.svg", fact: "„Love Me Do“ war der Startschuss für die erfolgreichste Band der Musikgeschichte." },
  { id: "jamesbond", title: "Der erste James-Bond-Film kommt ins Kino", year: 1962, image: "img/jamesbond.svg", fact: "In „James Bond jagt Dr. No“ spielte Sean Connery den Agenten 007." },
  { id: "algerien", title: "Algerien wird unabhängig", year: 1962, image: "img/algerien.svg", fact: "Nach einem achtjährigen Krieg gegen Frankreich wurde Algerien ein eigener Staat." },
  { id: "mlk", title: "Martin Luther King: „I Have a Dream“", year: 1963, image: "img/mlk.svg", fact: "Vor über 250.000 Menschen in Washington forderte King gleiche Rechte für Schwarze und Weiße." },
  { id: "jfk", title: "Attentat auf John F. Kennedy", year: 1963, image: "img/jfk.svg", fact: "Der US-Präsident wurde am 22. November in Dallas während einer Autofahrt erschossen." },
  { id: "bundesliga", title: "Die erste Bundesliga-Saison startet", year: 1963, image: "img/bundesliga.svg", fact: "Erster Meister der neuen Liga wurde der 1. FC Köln." },
  { id: "wembley", title: "Das Wembley-Tor", year: 1966, image: "img/wembley.svg", fact: "Im WM-Finale gegen Deutschland zählte ein Schuss von Geoff Hurst – ob der Ball hinter der Linie war, ist bis heute umstritten." },
  { id: "herz", title: "Erste Herztransplantation", year: 1967, image: "img/herz.svg", fact: "Der Chirurg Christiaan Barnard verpflanzte in Kapstadt erstmals ein menschliches Herz." },
  { id: "ltb", title: "Das erste Lustige Taschenbuch erscheint in Deutschland", year: 1967, image: "img/ltb.svg", fact: "Band 1 hieß „Der Kolumbusfalter“ – heute gibt es Hunderte Bände." },
  { id: "68er", title: "Studentenproteste der 68er-Bewegung", year: 1968, image: "img/68er.svg", fact: "Junge Menschen protestierten weltweit gegen den Vietnamkrieg und für mehr Mitbestimmung." },
  { id: "mondlandung", title: "Erste Mondlandung", year: 1969, image: "img/mondlandung.svg", fact: "Neil Armstrong betrat als erster Mensch den Mond." },
  { id: "fussballkrieg", title: "Der „Fußballkrieg“", year: 1969, image: "img/fussballkrieg.svg", fact: "Nach WM-Qualifikationsspielen eskalierte der Streit zwischen Honduras und El Salvador zu einem 100-Stunden-Krieg." },
  { id: "ibuprofen", title: "Ibuprofen kommt auf den Markt", year: 1969, image: "img/ibuprofen.svg", fact: "Das Schmerzmittel wurde in England entwickelt und kam dort zuerst in die Apotheken." },
  { id: "kniefall", title: "Kniefall von Warschau", year: 1970, image: "img/kniefall.svg", fact: "Bundeskanzler Willy Brandt kniete am Denkmal für die Opfer des Warschauer Ghettos nieder." },
  { id: "email", title: "Die erste E-Mail wird verschickt", year: 1971, image: "img/email.svg", fact: "Ray Tomlinson führte dafür das @-Zeichen in E-Mail-Adressen ein." },
  { id: "mcdonalds", title: "Erste deutsche McDonald’s-Filiale öffnet", year: 1971, image: "img/mcdonalds.svg", fact: "Die erste Filiale in Deutschland eröffnete am 4. Dezember in München." },
  { id: "ubahn_muc", title: "Die erste U-Bahn in München fährt", year: 1971, image: "img/ubahn_muc.svg", fact: "Rechtzeitig vor den Olympischen Spielen 1972 eröffnete die Strecke zwischen Kieferngarten und Goetheplatz." },
  { id: "olympia72", title: "Olympia-Attentat von München", year: 1972, image: "img/olympia72.svg", fact: "Palästinensische Terroristen überfielen die israelische Mannschaft; elf Sportler wurden getötet." },
  { id: "fielmann", title: "Gründung von Fielmann", year: 1972, image: "img/fielmann.svg", fact: "Günther Fielmann eröffnete sein erstes Brillengeschäft in Cuxhaven." },
  { id: "pong", title: "Das Videospiel „Pong“ erscheint", year: 1972, image: "img/pong.svg", fact: "Das simple Tennisspiel von Atari war der erste große Videospiel-Erfolg." },
  { id: "oelkrise", title: "Ölkrise – autofreie Sonntage", year: 1973, image: "img/oelkrise.svg", fact: "Weil Öl knapp und teuer wurde, waren in der Bundesrepublik an vier Sonntagen Autofahrten verboten." },
  { id: "bigmac", title: "Der Big Mac kommt nach Deutschland", year: 1973, image: "img/bigmac.svg", fact: "Zwei Jahre nach der ersten deutschen McDonald’s-Filiale kam der doppelstöckige Burger auf die Karte." },
  { id: "wm1974", title: "Deutschland wird im eigenen Land Weltmeister", year: 1974, image: "img/wm1974.svg", fact: "Im Finale in München traf Gerd Müller zum 2:1 gegen die Niederlande." },
  { id: "vietnam", title: "Ende des Vietnamkriegs", year: 1975, image: "img/vietnam.svg", fact: "Mit der Einnahme Saigons endete der jahrzehntelange Krieg." },
  { id: "apple", title: "Gründung von Apple", year: 1976, image: "img/apple.svg", fact: "Steve Jobs, Steve Wozniak und Ronald Wayne gründeten die Firma in Kalifornien." },
  { id: "burgerking", title: "Burger King eröffnet erstmals in Deutschland", year: 1976, image: "img/burgerking.svg", fact: "Die erste deutsche Filiale eröffnete am Kurfürstendamm in Berlin." },
  { id: "voyager", title: "Start der Raumsonden Voyager 1 und 2", year: 1977, image: "img/voyager.svg", fact: "Voyager 1 ist heute das am weitesten von der Erde entfernte von Menschen gebaute Objekt." },
  { id: "elvis", title: "Elvis Presley stirbt", year: 1977, image: "img/elvis.svg", fact: "Der „King of Rock ’n’ Roll“ starb mit 42 Jahren auf seinem Anwesen Graceland." },
  { id: "deutscher_herbst", title: "Der „Deutsche Herbst“", year: 1977, image: "img/deutscher_herbst.svg", fact: "Die Terrorgruppe RAF entführte und ermordete Arbeitgeberpräsident Hanns Martin Schleyer." },
  { id: "retortenbaby", title: "Erstes „Retortenbaby“ wird geboren", year: 1978, image: "img/retortenbaby.svg", fact: "Louise Brown war der erste Mensch, der durch künstliche Befruchtung im Labor entstand." },
  { id: "walkman", title: "Der Walkman kommt auf den Markt", year: 1979, image: "img/walkman.svg", fact: "Zum ersten Mal konnte man Musik überall mit Kopfhörern hören – auf Kassette." },
  { id: "freddie", title: "Freddie Mercury zieht nach München", year: 1979, approx: true, image: "img/freddie.svg", fact: "Der Queen-Sänger lebte von Ende der 1970er bis Mitte der 1980er überwiegend in München." },
  { id: "pocken", title: "Die Pocken sind ausgerottet", year: 1980, image: "img/pocken.svg", fact: "Dank weltweiter Impfungen war sie die erste Krankheit, die der Mensch vollständig besiegte." },
  { id: "lennon", title: "John Lennon wird erschossen", year: 1980, image: "img/lennon.svg", fact: "Der Ex-Beatle wurde am 8. Dezember vor seinem Wohnhaus in New York erschossen." },
  { id: "pc", title: "Der IBM Personal Computer erscheint", year: 1981, image: "img/pc.svg", fact: "Der „IBM PC“ machte den Computer zum Bürogerät." },
  { id: "aids", title: "Entdeckung von AIDS", year: 1981, image: "img/aids.svg", fact: "US-Ärzte beschrieben die ersten Fälle; 1983 wurde das auslösende HI-Virus entdeckt." },
  { id: "mtv", title: "MTV geht auf Sendung", year: 1981, image: "img/mtv.svg", fact: "Das erste Musikvideo auf dem Sender war passenderweise „Video Killed the Radio Star“." },
  { id: "sperrbezirk", title: "„Skandal im Sperrbezirk“ erscheint", year: 1981, image: "img/sperrbezirk.svg", fact: "Der Bayerische Rundfunk spielte den Song der Spider Murphy Gang zunächst nicht – trotzdem wurde er ein Riesenhit." },
  { id: "indianajones", title: "Der erste Indiana-Jones-Film kommt ins Kino", year: 1981, image: "img/indianajones.svg", fact: "In „Jäger des verlorenen Schatzes“ jagte Harrison Ford mit Hut und Peitsche nach der Bundeslade." },
  { id: "cd", title: "Die CD kommt auf den Markt", year: 1982, image: "img/cd.svg", fact: "Die silberne Scheibe löste nach und nach Schallplatte und Kassette ab." },
  { id: "falkland", title: "Falklandkrieg", year: 1982, image: "img/falkland.svg", fact: "Argentinien besetzte die britischen Falklandinseln – Großbritannien eroberte sie nach zehn Wochen zurück." },
  { id: "majortom", title: "„Major Tom (völlig losgelöst)“ erscheint", year: 1982, image: "img/majortom.svg", fact: "Peter Schillings Song über einen Astronauten wurde ein Nummer-eins-Hit der Neuen Deutschen Welle." },
  { id: "handy", title: "Das erste Handy kommt in den Handel", year: 1983, image: "img/handy.svg", fact: "Das Motorola DynaTAC wog rund 800 Gramm und kostete fast 4.000 Dollar." },
  { id: "luftballons", title: "„99 Luftballons“ erscheint", year: 1983, image: "img/luftballons.svg", fact: "Nenas Antikriegslied schaffte es sogar auf Platz 2 der US-Charts." },
  { id: "lifeislife", title: "„Life Is Life“ erscheint", year: 1984, image: "img/lifeislife.svg", fact: "Der Song der österreichischen Band Opus wurde 1985 in ganz Europa zum Sommerhit." },
  { id: "ozon", title: "Entdeckung des Ozonlochs", year: 1985, image: "img/ozon.svg", fact: "Forscher entdeckten über der Antarktis eine dünne Stelle in der schützenden Ozonschicht." },
  { id: "liveaid", title: "Live-Aid-Konzert", year: 1985, image: "img/liveaid.svg", fact: "Konzerte in London und Philadelphia sammelten Geld gegen die Hungersnot in Äthiopien – Queen gab einen legendären Auftritt." },
  { id: "becker", title: "Boris Becker gewinnt erstmals Wimbledon", year: 1985, image: "img/becker.svg", fact: "Mit 17 Jahren wurde er der jüngste Wimbledon-Sieger aller Zeiten – und gewann das Turnier danach noch zweimal." },
  { id: "ohnedich", title: "„Ohne dich (schlaf’ ich heut’ Nacht nicht ein)“ erscheint", year: 1985, image: "img/ohnedich.svg", fact: "Der größte Hit der Münchener Freiheit." },
  { id: "ryanair", title: "Erster Flug von Ryanair", year: 1985, image: "img/ryanair.svg", fact: "Die irische Fluglinie startete mit einem kleinen Propellerflugzeug von Waterford nach London." },
  { id: "lindenstrasse", title: "Die erste Folge der „Lindenstraße“", year: 1985, image: "img/lindenstrasse.svg", fact: "Die ARD-Serie lief fast 35 Jahre lang jeden Sonntag – bis 2020." },
  { id: "zurueckzukunft", title: "„Zurück in die Zukunft“ kommt ins Kino", year: 1985, image: "img/zurueckzukunft.svg", fact: "Marty McFly reist mit einem umgebauten DeLorean ins Jahr 1955." },
  { id: "tschernobyl", title: "Reaktorunglück von Tschernobyl", year: 1986, image: "img/tschernobyl.svg", fact: "Eine radioaktive Wolke zog bis nach Mitteleuropa." },
  { id: "alf", title: "Die Serie „ALF“ läuft erstmals", year: 1986, image: "img/alf.svg", fact: "Der Außerirdische vom Planeten Melmac liebt Katzen – am liebsten zum Essen." },
  { id: "challenger", title: "Explosion der Raumfähre Challenger", year: 1986, image: "img/challenger.svg", fact: "73 Sekunden nach dem Start kamen alle sieben Astronauten ums Leben – darunter eine Lehrerin." },
  { id: "hierkommtalex", title: "„Hier kommt Alex“ erscheint", year: 1988, image: "img/hierkommtalex.svg", fact: "Der Song der Toten Hosen ist vom Film „Uhrwerk Orange“ inspiriert." },
  { id: "mauerfall", title: "Fall der Berliner Mauer", year: 1989, image: "img/mauerfall.svg", fact: "Am 9. November öffnete die DDR die Grenzübergänge." },
  { id: "tiananmen", title: "Tian’anmen-Massaker in Peking", year: 1989, image: "img/tiananmen.svg", fact: "Die chinesische Armee schlug am 4. Juni die Proteste für Demokratie gewaltsam nieder." },
  { id: "pro7", title: "ProSieben geht auf Sendung", year: 1989, image: "img/pro7.svg", fact: "Der Privatsender startete am 1. Januar 1989." },
  { id: "simpsons", title: "„Die Simpsons“ laufen erstmals als eigene Serie", year: 1989, image: "img/simpsons.svg", fact: "Sie ist die am längsten laufende Zeichentrickserie im US-Fernsehen." },
  { id: "gameboy", title: "Der Game Boy erscheint", year: 1989, image: "img/gameboy.svg", fact: "Nintendos Handkonsole wurde mit dem Spiel Tetris zum Welterfolg." },
  { id: "wiedervereinigung", title: "Deutsche Wiedervereinigung", year: 1990, image: "img/wiedervereinigung.svg", fact: "Am 3. Oktober trat die DDR der Bundesrepublik bei." },
  { id: "hubble", title: "Das Hubble-Weltraumteleskop startet", year: 1990, image: "img/hubble.svg", fact: "Ohne störende Atmosphäre macht es gestochen scharfe Bilder ferner Galaxien." },
  { id: "mandela_frei", title: "Freilassung von Nelson Mandela", year: 1990, image: "img/mandela_frei.svg", fact: "Nach 27 Jahren Haft kam der Kämpfer gegen die Apartheid frei." },
  { id: "bierkoenig", title: "Der Bierkönig auf Mallorca wird eröffnet", year: 1990, image: "img/bierkoenig.svg", fact: "Der Frankfurter Wirt Manfred Meisel machte aus einer Kneipe in der Schinkenstraße einen Biergarten mit Freiluft-Disco." },
  { id: "verdammt", title: "„Verdammt, ich lieb’ dich“ erscheint", year: 1990, image: "img/verdammt.svg", fact: "Matthias Reims Debütsingle stand 16 Wochen auf Platz 1 der deutschen Charts." },
  { id: "wm1990", title: "Deutschland wird in Italien Weltmeister", year: 1990, image: "img/wm1990.svg", fact: "Andreas Brehme verwandelte im Finale gegen Argentinien den entscheidenden Elfmeter." },
  { id: "www", title: "Das World Wide Web geht online", year: 1991, image: "img/www.svg", fact: "Tim Berners-Lee entwickelte das WWW am Forschungszentrum CERN." },
  { id: "freddie_tod", title: "Freddie Mercury stirbt", year: 1991, image: "img/freddie_tod.svg", fact: "Der Queen-Sänger starb an den Folgen von AIDS – nur einen Tag, nachdem er seine Erkrankung öffentlich gemacht hatte." },
  { id: "jugoslawien", title: "Beginn der Jugoslawienkriege", year: 1991, image: "img/jugoslawien.svg", fact: "Nach der Unabhängigkeit Sloweniens und Kroatiens zerfiel Jugoslawien in blutigen Kriegen." },
  { id: "twix", title: "Aus Raider wird Twix", year: 1991, image: "img/twix.svg", fact: "„Raider heißt jetzt Twix – sonst ändert sich nix“: Mit diesem Slogan bekam der Schokoriegel in Deutschland seinen neuen Namen." },
  { id: "sms", title: "Die erste SMS wird verschickt", year: 1992, image: "img/sms.svg", fact: "Sie lautete „Merry Christmas“ und wurde von einem Computer an ein Handy geschickt." },
  { id: "dahmer", title: "Jeffrey Dahmer wird verurteilt", year: 1992, image: "img/dahmer.svg", fact: "Der Serienmörder aus Milwaukee erhielt 15-mal lebenslang." },
  { id: "eu", title: "Gründung der Europäischen Union", year: 1993, image: "img/eu.svg", fact: "Mit dem Vertrag von Maastricht wurde aus der Europäischen Gemeinschaft die EU." },
  { id: "eritrea", title: "Eritrea wird unabhängig", year: 1993, image: "img/eritrea.svg", fact: "Nach 30 Jahren Krieg gegen Äthiopien stimmten fast 100 % der Eritreer für die Unabhängigkeit." },
  { id: "mandela", title: "Nelson Mandela wird Präsident Südafrikas", year: 1994, image: "img/mandela.svg", fact: "Nach dem Ende der Apartheid durften erstmals alle Südafrikaner wählen." },
  { id: "cobain", title: "Kurt Cobain stirbt", year: 1994, image: "img/cobain.svg", fact: "Der Sänger von Nirvana („Smells Like Teen Spirit“) starb mit nur 27 Jahren." },
  { id: "playstation", title: "Die erste PlayStation erscheint", year: 1994, image: "img/playstation.svg", fact: "Die Spielkonsole von Sony kam zuerst in Japan heraus, 1995 dann auch in Europa." },
  { id: "friends", title: "Die Serie „Friends“ startet", year: 1994, image: "img/friends.svg", fact: "Zehn Staffeln lang trafen sich die sechs Freunde im Café „Central Perk“ in New York." },
  { id: "qrcode", title: "Der QR-Code wird erfunden", year: 1994, image: "img/qrcode.svg", fact: "Die japanische Firma Denso Wave entwickelte ihn, um Autoteile in Fabriken schneller zu erfassen." },
  { id: "db_ag", title: "Gründung der Deutschen Bahn AG", year: 1994, image: "img/db_ag.svg", fact: "Die westdeutsche Bundesbahn und die ostdeutsche Reichsbahn wurden zur Deutschen Bahn AG zusammengelegt." },
  { id: "qatar", title: "Qatar Airways nimmt den Flugbetrieb auf", year: 1994, image: "img/qatar.svg", fact: "Die Fluglinie startete mit nur zwei geleasten Flugzeugen – heute gehört sie zu den größten der Welt." },
  { id: "koenigloewen", title: "„Der König der Löwen“ kommt ins Kino", year: 1994, image: "img/koenigloewen.svg", fact: "Der Disney-Film um den jungen Löwen Simba wurde einer der erfolgreichsten Zeichentrickfilme aller Zeiten." },
  { id: "pulpfiction", title: "„Pulp Fiction“ startet in den deutschen Kinos", year: 1994, image: "img/pulpfiction.svg", fact: "Quentin Tarantinos Film gewann die Goldene Palme in Cannes und den Oscar für das beste Drehbuch." },
  { id: "effenberg", title: "Effenberg zeigt bei der WM den Stinkefinger", year: 1994, image: "img/effenberg.svg", fact: "Nach Pfiffen der eigenen Fans zeigte Stefan Effenberg in den USA den Mittelfinger – Bundestrainer Vogts warf ihn aus dem Kader." },
  { id: "ebay", title: "Gründung von eBay", year: 1995, image: "img/ebay.svg", fact: "Pierre Omidyar startete die Auktionsseite – zuerst unter dem Namen „AuctionWeb“." },
  { id: "superrtl", title: "Super RTL geht auf Sendung", year: 1995, image: "img/superrtl.svg", fact: "Der Kindersender startete am 28. April 1995." },
  { id: "dolly", title: "Klonschaf Dolly wird geboren", year: 1996, image: "img/dolly.svg", fact: "Dolly war das erste aus einer erwachsenen Körperzelle geklonte Säugetier." },
  { id: "tupac", title: "Tupac wird in Las Vegas erschossen", year: 1996, image: "img/tupac.svg", fact: "Der Rapper wurde aus einem Auto heraus angeschossen und starb sechs Tage später." },
  { id: "harry_potter", title: "Der erste Harry-Potter-Band erscheint", year: 1997, image: "img/harry_potter.svg", fact: "„Harry Potter und der Stein der Weisen“ von J. K. Rowling wurde ein Welterfolg." },
  { id: "teresa", title: "Mutter Teresa stirbt", year: 1997, image: "img/teresa.svg", fact: "Die Ordensfrau half jahrzehntelang den Ärmsten in Kalkutta und erhielt den Friedensnobelpreis." },
  { id: "diana", title: "Tod von Prinzessin Diana", year: 1997, image: "img/diana.svg", fact: "Die „Prinzessin der Herzen“ starb bei einem Autounfall in Paris." },
  { id: "netflix", title: "Gründung von Netflix", year: 1997, image: "img/netflix.svg", fact: "Netflix begann als Versanddienst, der DVDs per Post verlieh." },
  { id: "tyson", title: "Mike Tyson beißt Holyfield ein Stück Ohr ab", year: 1997, image: "img/tyson.svg", fact: "Im Rückkampf gegen Evander Holyfield wurde Tyson danach disqualifiziert." },
  { id: "teletubbies", title: "Die Teletubbies laufen erstmals im Fernsehen", year: 1997, image: "img/teletubbies.svg", fact: "Tinky Winky, Dipsy, Laa-Laa und Po starteten in Großbritannien – nach Deutschland kamen sie 1999." },
  { id: "iss", title: "Baubeginn der Raumstation ISS", year: 1998, image: "img/iss.svg", fact: "Das erste Modul „Sarja“ wurde ins All geschossen – heute ist die ISS so groß wie ein Fußballfeld." },
  { id: "google", title: "Gründung von Google", year: 1998, image: "img/google.svg", fact: "Larry Page und Sergey Brin starteten die Suchmaschine in einer Garage in Kalifornien." },
  { id: "fck1998", title: "Der 1. FC Kaiserslautern wird als Aufsteiger Meister", year: 1998, image: "img/fck1998.svg", fact: "Unter Otto Rehhagel gelang dem FCK, was in der Bundesliga noch nie jemand geschafft hatte." },
  { id: "schroeder", title: "Gerhard Schröder wird Bundeskanzler", year: 1998, image: "img/schroeder.svg", fact: "Die erste rot-grüne Bundesregierung löste nach 16 Jahren Helmut Kohl ab." },
  { id: "familyguy", title: "„Family Guy“ läuft erstmals", year: 1999, image: "img/familyguy.svg", fact: "Die Zeichentrickserie um Peter Griffin, Baby Stewie und Hund Brian startete direkt nach dem Super Bowl." },
  { id: "tvtotal", title: "Die erste Folge von „TV total“", year: 1999, image: "img/tvtotal.svg", fact: "Stefan Raab zeigte die lustigsten Fernsehpannen – und drückte dazu auf den „Raab-Knopf“." },
  { id: "wwm", title: "Die erste Folge von „Wer wird Millionär?“", year: 1999, image: "img/wwm.svg", fact: "Günther Jauch moderierte die Quizshow auf RTL – mit Publikumsjoker und Telefonjoker." },
  { id: "cdu_spenden", title: "Die CDU-Spendenaffäre wird bekannt", year: 1999, image: "img/cdu_spenden.svg", fact: "Altkanzler Helmut Kohl hatte Parteispenden auf schwarzen Konten angenommen und die Spender nie genannt." },
  { id: "putin", title: "Wladimir Putin wird erstmals Präsident Russlands", year: 2000, image: "img/putin.svg", fact: "Er übernahm das Amt von Boris Jelzin und wurde im März 2000 gewählt." },
  { id: "figo", title: "Luís Figo wechselt vom FC Barcelona zu Real Madrid", year: 2000, image: "img/figo.svg", fact: "Der Wechsel zum Erzrivalen machte ihn in Barcelona zum Hassobjekt – Fans warfen sogar einen Schweinekopf aufs Feld." },
  { id: "bigbrother", title: "„Big Brother“ startet im deutschen Fernsehen", year: 2000, image: "img/bigbrother.svg", fact: "Zum ersten Mal wurden Menschen rund um die Uhr in einem Wohncontainer gefilmt." },
  { id: "wikipedia", title: "Wikipedia geht online", year: 2001, image: "img/wikipedia.svg", fact: "Die freie Online-Enzyklopädie wird von Freiwilligen auf der ganzen Welt geschrieben." },
  { id: "nine_eleven", title: "Terroranschläge vom 11. September", year: 2001, image: "img/nine_eleven.svg", fact: "Terroristen steuerten entführte Flugzeuge in das World Trade Center und das Pentagon; fast 3.000 Menschen starben." },
  { id: "herrderringe", title: "Der erste „Herr der Ringe“-Film kommt ins Kino", year: 2001, image: "img/herrderringe.svg", fact: "„Die Gefährten“ von Peter Jackson war der Auftakt der Trilogie, die insgesamt 17 Oscars gewann." },
  { id: "euro", title: "Euro-Bargeld wird eingeführt", year: 2002, image: "img/euro.svg", fact: "Am 1. Januar löste der Euro u. a. die D-Mark ab." },
  { id: "dsds", title: "Die erste Staffel von „Deutschland sucht den Superstar“", year: 2002, image: "img/dsds.svg", fact: "Gewinner der ersten Staffel wurde Alexander Klaws, Juror war unter anderem Dieter Bohlen." },
  { id: "genom", title: "Das menschliche Erbgut ist entschlüsselt", year: 2003, image: "img/genom.svg", fact: "Das Humangenomprojekt las die rund 3 Milliarden Bausteine unserer DNA aus." },
  { id: "hilton", title: "Privates Sexvideo von Paris Hilton wird geleakt", year: 2003, image: "img/hilton.svg", fact: "Das Video wurde ohne ihre Zustimmung veröffentlicht und verbreitete sich rasant im Internet." },
  { id: "fluchkaribik", title: "„Fluch der Karibik“ startet in den deutschen Kinos", year: 2003, image: "img/fluchkaribik.svg", fact: "Johnny Depp wurde als Captain Jack Sparrow weltberühmt." },
  { id: "facebook", title: "Gründung von Facebook", year: 2004, image: "img/facebook.svg", fact: "Mark Zuckerberg startete das soziale Netzwerk als Student an der Harvard-Universität." },
  { id: "tsunami", title: "Tsunami im Indischen Ozean", year: 2004, image: "img/tsunami.svg", fact: "Ein Seebeben löste am 26. Dezember eine Riesenwelle aus, die über 200.000 Menschen tötete." },
  { id: "invincibles", title: "Arsenals „Invincibles“-Saison", year: 2004, image: "img/invincibles.svg", fact: "Der FC Arsenal wurde englischer Meister, ohne ein einziges Ligaspiel zu verlieren." },
  { id: "nipplegate", title: "„Nipplegate“ beim Super Bowl", year: 2004, image: "img/nipplegate.svg", fact: "Bei der Halbzeitshow entblößte Justin Timberlake kurz die Brust von Janet Jackson – ein Riesenskandal in den USA." },
  { id: "merkel", title: "Angela Merkel wird erste Bundeskanzlerin", year: 2005, image: "img/merkel.svg", fact: "Sie regierte 16 Jahre lang – bis 2021." },
  { id: "youtube", title: "Das erste YouTube-Video wird hochgeladen", year: 2005, image: "img/youtube.svg", fact: "In „Me at the zoo“ filmte sich Mitgründer Jawed Karim 19 Sekunden lang vor Elefanten im Zoo von San Diego." },
  { id: "hoyzer", title: "Der Hoyzer-Skandal", year: 2005, image: "img/hoyzer.svg", fact: "Schiedsrichter Robert Hoyzer hatte Spiele für Geld von Wettbetrügern manipuliert." },
  { id: "wirsindpapst", title: "„Wir sind Papst!“", year: 2005, image: "img/wirsindpapst.svg", fact: "Mit Joseph Ratzinger (Benedikt XVI.) wurde erstmals seit fast 500 Jahren ein Deutscher Papst." },
  { id: "wm2006", title: "Fußball-WM in Deutschland – das „Sommermärchen“", year: 2006, image: "img/wm2006.svg", fact: "Deutschland feierte als Gastgeber und wurde Dritter." },
  { id: "loew", title: "Joachim Löw wird Bundestrainer", year: 2006, image: "img/loew.svg", fact: "Nach der Heim-WM übernahm er von Jürgen Klinsmann und gewann 2014 den WM-Titel." },
  { id: "zidane", title: "Zidanes Kopfstoß gegen Materazzi", year: 2006, image: "img/zidane.svg", fact: "Im WM-Finale in Berlin sah Zidane Rot – Italien gewann danach im Elfmeterschießen gegen Frankreich." },
  { id: "giesinger", title: "Gründung der Giesinger Brauerei", year: 2006, image: "img/giesinger.svg", fact: "Steffen Marx begann in einer Garage in München-Giesing zu brauen – heute ist sie eine große Münchner Brauerei." },
  { id: "gntm", title: "Die erste Staffel von „Germany’s Next Topmodel“", year: 2006, image: "img/gntm.svg", fact: "Heidi Klum suchte zum ersten Mal ein Model – Gewinnerin wurde Lena Gercke." },
  { id: "smartphone", title: "Das erste iPhone wird vorgestellt", year: 2007, image: "img/smartphone.svg", fact: "Es machte Touchscreen-Smartphones massentauglich." },
  { id: "finanzkrise", title: "Weltfinanzkrise – Pleite von Lehman Brothers", year: 2008, image: "img/finanzkrise.svg", fact: "Der Zusammenbruch der US-Bank löste eine weltweite Wirtschaftskrise aus." },
  { id: "bitcoin", title: "Bitcoin – die erste Kryptowährung startet", year: 2009, image: "img/bitcoin.svg", fact: "Wer sich hinter dem Erfinder „Satoshi Nakamoto“ verbirgt, ist bis heute unbekannt." },
  { id: "obama", title: "Barack Obama wird US-Präsident", year: 2009, image: "img/obama.svg", fact: "Er war der erste afroamerikanische Präsident der USA." },
  { id: "wolfsburg", title: "Der VfL Wolfsburg wird Deutscher Meister", year: 2009, image: "img/wolfsburg.svg", fact: "Unter Trainer Felix Magath holte der VfL seine bisher einzige Meisterschaft." },
  { id: "jackson", title: "Michael Jackson stirbt", year: 2009, image: "img/jackson.svg", fact: "Der „King of Pop“ starb kurz vor seiner geplanten Comeback-Tour mit 50 Jahren." },
  { id: "cr7", title: "Cristiano Ronaldo wechselt von Manchester United zu Real Madrid", year: 2009, image: "img/cr7.svg", fact: "Die Ablöse von rund 94 Millionen Euro war damals Weltrekord." },
  { id: "doodlejump", title: "Doodle Jump erscheint", year: 2009, image: "img/doodlejump.svg", fact: "In dem Handyspiel hüpft ein kleines Wesen auf Plattformen immer weiter nach oben." },
  { id: "angrybirds", title: "Angry Birds erscheint", year: 2009, image: "img/angrybirds.svg", fact: "Mit der Schleuder schießt man wütende Vögel auf grüne Schweine – eines der erfolgreichsten Handyspiele aller Zeiten." },
  { id: "rihanna", title: "Chris Brown schlägt Rihanna", year: 2009, image: "img/rihanna.svg", fact: "Der Angriff in der Nacht vor den Grammys löste eine weltweite Debatte über Gewalt in Beziehungen aus." },
  { id: "arabischer_fruehling", title: "Beginn des Arabischen Frühlings", year: 2010, image: "img/arabischer_fruehling.svg", fact: "Proteste in Tunesien breiteten sich auf viele arabische Länder aus." },
  { id: "instagram", title: "Instagram geht online", year: 2010, image: "img/instagram.svg", fact: "Die Foto-App startete im Oktober zunächst nur für das iPhone – 2012 kaufte Facebook sie für 1 Milliarde Dollar." },
  { id: "s21", title: "Baubeginn von Stuttgart 21", year: 2010, image: "img/s21.svg", fact: "Das umstrittene Bahnprojekt löste große Proteste aus und wird viel teurer und später fertig als geplant." },
  { id: "lena", title: "Lena gewinnt den Eurovision Song Contest", year: 2010, image: "img/lena.svg", fact: "Mit „Satellite“ holte sie den ersten deutschen ESC-Sieg seit Nicole 1982." },
  { id: "fukushima", title: "Atomkatastrophe von Fukushima", year: 2011, image: "img/fukushima.svg", fact: "Ein Erdbeben und ein Tsunami zerstörten das Kraftwerk; Deutschland beschloss danach den Atomausstieg." },
  { id: "snapchat", title: "Snapchat geht online", year: 2011, image: "img/snapchat.svg", fact: "Das Besondere: Fotos verschwinden nach wenigen Sekunden wieder." },
  { id: "kim", title: "Kim Jong-un übernimmt die Macht in Nordkorea", year: 2011, image: "img/kim.svg", fact: "Nach dem Tod seines Vaters Kim Jong-il wurde er Machthaber – in dritter Generation der Familie." },
  { id: "sheen", title: "Charlie Sheen fliegt bei „Two and a Half Men“ raus", year: 2011, image: "img/sheen.svg", fact: "Nach Ausfällen und öffentlichen Angriffen auf den Produzenten wurde er gefeuert – Ashton Kutcher übernahm." },
  { id: "suedsudan", title: "Südsudan wird unabhängig", year: 2011, image: "img/suedsudan.svg", fact: "Der Südsudan ist der jüngste allgemein anerkannte Staat der Welt." },
  { id: "curiosity", title: "Mars-Rover Curiosity landet", year: 2012, image: "img/curiosity.svg", fact: "Der Rover in Autogröße fand Hinweise, dass es auf dem Mars einst Wasser gab." },
  { id: "gangnam", title: "„Gangnam Style“ erscheint auf YouTube", year: 2012, image: "img/gangnam.svg", fact: "Das Video des südkoreanischen Rappers PSY war das erste auf YouTube mit über einer Milliarde Aufrufen." },
  { id: "higgs", title: "Entdeckung des Higgs-Teilchens", year: 2012, image: "img/higgs.svg", fact: "Am Forschungszentrum CERN wiesen Physiker das lange gesuchte Teilchen nach." },
  { id: "klumseal", title: "Heidi Klum und Seal trennen sich", year: 2012, image: "img/klumseal.svg", fact: "Nach fast sieben Jahren Ehe gab das Paar im Januar seine Trennung bekannt." },
  { id: "afd", title: "Gründung der AfD", year: 2013, image: "img/afd.svg", fact: "Die „Alternative für Deutschland“ wurde zunächst als eurokritische Partei gegründet." },
  { id: "wrecking_ball", title: "Miley Cyrus veröffentlicht „Wrecking Ball“", year: 2013, image: "img/wrecking_ball.svg", fact: "Das Musikvideo, in dem sie auf einer Abrissbirne sitzt, stellte einen Aufrufrekord auf." },
  { id: "snowden", title: "Snowden-Enthüllungen", year: 2013, image: "img/snowden.svg", fact: "Edward Snowden machte öffentlich, wie Geheimdienste weltweit Internet und Telefone überwachen." },
  { id: "harlemshake", title: "Der „Harlem Shake“ wird zum Internet-Hype", year: 2013, image: "img/harlemshake.svg", fact: "Tausende Gruppen filmten sich, wie erst einer und dann plötzlich alle wild tanzen." },
  { id: "atemlos", title: "Helene Fischer veröffentlicht „Atemlos durch die Nacht“", year: 2013, image: "img/atemlos.svg", fact: "Der Song wurde zum größten Schlager-Hit der 2010er-Jahre." },
  { id: "jokoklaas", title: "Joko & Klaas wechseln zu ProSieben", year: 2013, image: "img/jokoklaas.svg", fact: "Nach ihrer Zeit bei MTV und ZDFneo bekamen sie einen Exklusivvertrag – später folgte „Joko & Klaas gegen ProSieben“." },
  { id: "schumacher", title: "Michael Schumachers Skiunfall", year: 2013, image: "img/schumacher.svg", fact: "Der siebenfache Formel-1-Weltmeister stürzte in Méribel in den französischen Alpen schwer." },
  { id: "wm2014", title: "Deutschland wird Fußball-Weltmeister in Brasilien", year: 2014, image: "img/wm2014.svg", fact: "Mario Götze schoss im Finale gegen Argentinien das 1:0 – der vierte WM-Titel." },
  { id: "robin_williams", title: "Robin Williams stirbt", year: 2014, image: "img/robin_williams.svg", fact: "Der Schauspieler („Mrs. Doubtfire“, Stimme des Dschinni in „Aladdin“) starb mit 63 Jahren." },
  { id: "wiesn", title: "Die Maß auf der Wiesn kostet erstmals über 10 €", year: 2014, image: "img/wiesn.svg", fact: "Auf dem Oktoberfest kostete die Maß Bier bis zu 10,10 Euro." },
  { id: "erdogan", title: "Recep Tayyip Erdoğan wird erstmals Präsident der Türkei", year: 2014, image: "img/erdogan.svg", fact: "Zuvor war er bereits elf Jahre lang Ministerpräsident gewesen." },
  { id: "icebucket", title: "Die Ice Bucket Challenge geht viral", year: 2014, image: "img/icebucket.svg", fact: "Menschen schütteten sich Eiswasser über den Kopf, um Spenden für die Erforschung der Krankheit ALS zu sammeln." },
  { id: "hoeness", title: "Uli Hoeneß wird wegen Steuerhinterziehung verurteilt", year: 2014, image: "img/hoeness.svg", fact: "Der Bayern-Präsident bekam dreieinhalb Jahre Haft und trat sie noch im selben Jahr an." },
  { id: "paris_klima", title: "Pariser Klimaabkommen", year: 2015, image: "img/paris_klima.svg", fact: "Fast alle Staaten der Welt einigten sich, die Erderwärmung deutlich unter 2 °C zu halten." },
  { id: "vw", title: "VW-Abgasskandal („Dieselgate“)", year: 2015, image: "img/vw.svg", fact: "Volkswagen hatte mit einer Software die Abgaswerte von Millionen Dieselautos manipuliert." },
  { id: "charliehebdo", title: "Anschlag auf Charlie Hebdo", year: 2015, image: "img/charliehebdo.svg", fact: "Islamistische Terroristen töteten in Paris zwölf Menschen in der Redaktion des Satiremagazins." },
  { id: "adele", title: "Adele veröffentlicht „Hello“", year: 2015, image: "img/adele.svg", fact: "Das Video wurde in nur 24 Stunden fast 28 Millionen Mal angesehen – damals ein Rekord." },
  { id: "footballleaks", title: "Football Leaks gehen online", year: 2015, image: "img/footballleaks.svg", fact: "Der Portugiese Rui Pinto veröffentlichte geheime Verträge und Dokumente aus dem Profifußball." },
  { id: "wirschaffendas", title: "Merkel sagt „Wir schaffen das“", year: 2015, image: "img/wirschaffendas.svg", fact: "Mit diesem Satz reagierte die Kanzlerin auf die große Zahl Geflüchteter, die nach Deutschland kamen." },
  { id: "brexit", title: "Brexit-Abstimmung in Großbritannien", year: 2016, image: "img/brexit.svg", fact: "Knapp 52 % stimmten für den Austritt aus der EU, der 2020 vollzogen wurde." },
  { id: "leicester", title: "Leicester City wird englischer Meister", year: 2016, image: "img/leicester.svg", fact: "Die Wettquoten vor der Saison standen bei 5000:1 – eine der größten Sensationen der Fußballgeschichte." },
  { id: "lombardi", title: "Pietros „Schlampen“-Video taucht auf", year: 2016, image: "img/lombardi.svg", fact: "Sarah Lombardi veröffentlichte ein Handyvideo, in dem Pietro sie beschimpfte – kurz nach ihrer Trennung." },
  { id: "pokemongo", title: "Pokémon Go wird zum Hype", year: 2016, image: "img/pokemongo.svg", fact: "Weltweit liefen Millionen Menschen mit dem Handy durch die Straßen, um Pokémon zu fangen." },
  { id: "trump", title: "Donald Trump wird US-Präsident", year: 2017, image: "img/trump.svg", fact: "Der Unternehmer und frühere TV-Star trat im Januar 2017 sein Amt als 45. Präsident der USA an." },
  { id: "metoo", title: "Die #MeToo-Bewegung", year: 2017, image: "img/metoo.svg", fact: "Nach Berichten über Harvey Weinstein teilten Millionen Frauen unter #MeToo ihre Erfahrungen mit sexueller Belästigung." },
  { id: "neymar", title: "Neymar wechselt für 222 Mio. € zu Paris", year: 2017, image: "img/neymar.svg", fact: "Paris Saint-Germain zahlte dem FC Barcelona die höchste Ablösesumme der Fußballgeschichte." },
  { id: "ehefueralle", title: "Der Bundestag beschließt die „Ehe für alle“", year: 2017, image: "img/ehefueralle.svg", fact: "Seitdem dürfen auch gleichgeschlechtliche Paare in Deutschland heiraten." },
  { id: "greta", title: "Greta Thunbergs Schulstreik – Beginn von „Fridays for Future“", year: 2018, image: "img/greta.svg", fact: "Daraus entstand die weltweite Bewegung „Fridays for Future“." },
  { id: "relotius", title: "Die Relotius-Affäre beim Spiegel", year: 2018, image: "img/relotius.svg", fact: "Der preisgekrönte Reporter Claas Relotius hatte viele seiner Reportagen ganz oder teilweise erfunden." },
  { id: "schwarzes_loch", title: "Erstes Foto eines Schwarzen Lochs", year: 2019, image: "img/schwarzes_loch.svg", fact: "Acht Radioteleskope rund um die Welt arbeiteten dafür wie ein einziges, erdgroßes Teleskop zusammen." },
  { id: "epstein", title: "Jeffrey Epstein wird festgenommen", year: 2019, image: "img/epstein.svg", fact: "Der US-Multimillionär wurde wegen Menschenhandels mit Minderjährigen angeklagt und starb wenige Wochen später in Haft." },
  { id: "bereal", title: "Die App BeReal erscheint", year: 2019, image: "img/bereal.svg", fact: "Einmal am Tag zur gleichen Zeit ein Foto mit Front- und Rückkamera – der große Hype kam 2022." },
  { id: "notredame", title: "Brand der Kathedrale Notre-Dame in Paris", year: 2019, image: "img/notredame.svg", fact: "Der Dachstuhl und der Spitzturm brannten ab – im Dezember 2024 wurde die Kirche wiedereröffnet." },
  { id: "corona", title: "Corona-Pandemie", year: 2020, image: "img/corona.svg", fact: "Die WHO erklärte COVID-19 im März 2020 zur Pandemie." },
  { id: "harry", title: "Prinz Harry zieht sich aus dem Königshaus zurück", year: 2020, image: "img/harry.svg", fact: "Harry und Meghan gaben ihre Rolle als arbeitende Royals auf und zogen nach Kalifornien („Megxit“)." },
  { id: "webb", title: "Start des James-Webb-Weltraumteleskops", year: 2021, image: "img/webb.svg", fact: "Sein goldener Spiegel aus 18 Segmenten blickt bis kurz nach dem Urknall zurück." },
  { id: "kapitol", title: "Sturm auf das US-Kapitol", year: 2021, image: "img/kapitol.svg", fact: "Anhänger von Donald Trump stürmten am 6. Januar das Parlamentsgebäude in Washington." },
  { id: "evergiven", title: "Die „Ever Given“ steckt im Suezkanal fest", year: 2021, image: "img/evergiven.svg", fact: "Das riesige Containerschiff blockierte sechs Tage lang eine der wichtigsten Handelsrouten der Welt." },
  { id: "squidgame", title: "„Squid Game“ erscheint auf Netflix", year: 2021, image: "img/squidgame.svg", fact: "Die südkoreanische Serie wurde zur meistgesehenen Netflix-Serie ihrer Zeit." },
  { id: "messi_psg", title: "Messi wechselt vom FC Barcelona zu Paris Saint-Germain", year: 2021, image: "img/messi_psg.svg", fact: "Nach 21 Jahren bei Barça musste er gehen, weil der Verein sein Gehalt nicht mehr bezahlen konnte." },
  { id: "scholz", title: "Olaf Scholz wird Bundeskanzler", year: 2021, image: "img/scholz.svg", fact: "Er führte die erste Ampel-Koalition aus SPD, Grünen und FDP an." },
  { id: "chatgpt", title: "KI-Chatbot ChatGPT wird veröffentlicht", year: 2022, image: "img/chatgpt.svg", fact: "Innerhalb von zwei Monaten nutzten ihn rund 100 Millionen Menschen." },
  { id: "ukraine", title: "Russland greift die Ukraine an", year: 2022, image: "img/ukraine.svg", fact: "Am 24. Februar begann der russische Großangriff auf das ganze Land." },
  { id: "will_smith", title: "Will Smiths Ohrfeige bei den Oscars", year: 2022, image: "img/will_smith.svg", fact: "Will Smith ohrfeigte auf der Bühne den Moderator Chris Rock – kurz darauf gewann er den Oscar als bester Hauptdarsteller." },
  { id: "messi", title: "Messi wird mit Argentinien Weltmeister", year: 2022, image: "img/messi.svg", fact: "Im Finale in Katar besiegte Argentinien Frankreich nach einem 3:3 im Elfmeterschießen." },
  { id: "musk_twitter", title: "Elon Musk kauft Twitter", year: 2022, image: "img/musk_twitter.svg", fact: "Er zahlte rund 44 Milliarden Dollar und benannte den Dienst später in „X“ um." },
  { id: "queen", title: "Tod von Queen Elizabeth II.", year: 2022, image: "img/queen.svg", fact: "Sie regierte 70 Jahre lang – länger als jeder andere britische Monarch." },
  { id: "deppheard", title: "Prozess Johnny Depp gegen Amber Heard beginnt", year: 2022, image: "img/deppheard.svg", fact: "Der Verleumdungsprozess wurde live übertragen und auf TikTok millionenfach kommentiert." },
  { id: "becker_haft", title: "Boris Becker wird in London zu einer Haftstrafe verurteilt", year: 2022, image: "img/becker_haft.svg", fact: "Wegen Verstößen im Insolvenzverfahren bekam er zweieinhalb Jahre – nach acht Monaten kam er frei." },
  { id: "atomausstieg", title: "Deutschland schaltet die letzten Atomkraftwerke ab", year: 2023, image: "img/atomausstieg.svg", fact: "Am 15. April 2023 gingen die drei letzten deutschen Kernkraftwerke vom Netz." },
  { id: "barbenheimer", title: "„Barbenheimer“: Barbie und Oppenheimer starten", year: 2023, image: "img/barbenheimer.svg", fact: "Beide Filme kamen am selben Tag in die Kinos und wurden gemeinsam zum Internet-Phänomen." },
  { id: "erastour", title: "Taylor Swifts „Eras Tour“ beginnt", year: 2023, image: "img/erastour.svg", fact: "Sie wurde zur umsatzstärksten Konzerttournee aller Zeiten." },
  { id: "diddy", title: "Der Skandal um P. Diddy wird öffentlich", year: 2023, image: "img/diddy.svg", fact: "Seine Ex-Partnerin Cassie reichte im November Klage ein; 2024 wurde Sean Combs festgenommen." },
  { id: "hamas", title: "Terrorangriff der Hamas auf Israel", year: 2023, image: "img/hamas.svg", fact: "Am 7. Oktober töteten Terroristen rund 1.200 Menschen und verschleppten über 250 Geiseln – danach begann der Gaza-Krieg." },
  { id: "olympia_paris", title: "Olympische Sommerspiele in Paris", year: 2024, image: "img/olympia_paris.svg", fact: "Die Eröffnungsfeier fand erstmals nicht in einem Stadion statt, sondern auf der Seine." },
  { id: "hawktuah", title: "„Hawk Tuah“ wird zum viralen Meme", year: 2024, image: "img/hawktuah.svg", fact: "Ein kurzer Ausschnitt aus einem Straßeninterview ging weltweit durch die sozialen Netzwerke." },
  { id: "lindner", title: "Olaf Scholz entlässt Finanzminister Christian Lindner", year: 2024, image: "img/lindner.svg", fact: "Damit zerbrach die Ampel-Koalition; im Februar 2025 folgte eine vorgezogene Bundestagswahl." },
  { id: "cannabis", title: "Cannabis wird in Deutschland teilweise legalisiert", year: 2024, image: "img/cannabis.svg", fact: "Seit dem 1. April 2024 dürfen Erwachsene in begrenzter Menge Cannabis besitzen und anbauen." },
  { id: "brangelina", title: "Brad Pitt und Angelina Jolie sind offiziell geschieden", year: 2024, image: "img/brangelina.svg", fact: "Nach mehr als acht Jahren Rechtsstreit einigten sie sich Ende Dezember." },
  { id: "em2024", title: "Fußball-EM in Deutschland", year: 2024, image: "img/em2024.svg", fact: "Europameister wurde Spanien, das Deutschland im Viertelfinale besiegte." },
  { id: "papst", title: "Leo XIV. – erster Papst aus den USA", year: 2025, image: "img/papst.svg", fact: "Der in Chicago geborene Robert Francis Prevost wurde im Mai 2025 zum Papst gewählt." },
  { id: "merz", title: "Friedrich Merz wird Bundeskanzler", year: 2025, image: "img/merz.svg", fact: "Er wurde erst im zweiten Wahlgang gewählt – das gab es in der Bundesrepublik noch nie." },
  { id: "wm2026", title: "Erste Fußball-WM mit 48 Mannschaften", year: 2026, image: "img/wm2026.svg", fact: "Das Turnier wurde erstmals in drei Ländern ausgetragen: USA, Kanada und Mexiko." },
  { id: "klopp", title: "Jürgen Klopp wird Bundestrainer", year: 2026, image: "img/klopp.svg", fact: "Nach dem WM-Aus übernahm Klopp die Nationalmannschaft mit einem Vertrag bis zur WM 2030." },
  { id: "swiftkelce", title: "Taylor Swift und Travis Kelce heiraten", year: 2026, image: "img/swiftkelce.svg", fact: "Die Hochzeit fand am 3. Juli 2026 im Madison Square Garden in New York statt." },
];
